var PLACES=[
 {t:"Shenzhen",s:"La ciudad más tecnológica del mundo, y no es exageración de folleto",
  x:"El clúster Shenzhen, Hong Kong y Cantón es el número uno mundial en el índice de innovación de la WIPO, por delante de Tokio y de San Francisco. Lo interesante para un turista es que aquí la tecnología no está en una oficina: está en la calle, en la cadena de suministro.",
  i:[["shenzhen_2","Huaqiangbei: 35 mercados especializados, más de 115.000 negocios"],
     ["shenzhen_3","Ping An Finance Center, 599 metros"],
     ["shenzhen_1","De pueblo pesquero a 17 millones de habitantes en cuarenta años"]],
  r:[1,2,3,4,6]},
 {t:"Altiplano de Qinghai",s:"El refugio climático que solo funciona en agosto",only:"Solo en agosto",
  x:"Mientras Xi'an pasa de 38 grados, Xining se queda en 22 a 25. El lago Qinghai está a 3.200 metros y es cuatro veces el lago de Ginebra; Chaka, a 3.059, es una costra de sal que refleja el cielo entero. De finales de junio a principios de agosto la orilla se llena de colza en flor. En mayo esto está pelado y frío: es literalmente la única ventana del año.",
  i:[["qinghai_2","La colza en flor a orillas del lago, hasta principios de agosto"],
     ["qinghai_1","El mayor lago salado de China, a 3.200 metros"],
     ["chaka_1","Chaka, el espejo del cielo, a 3.059 metros"],
     ["xining_1","Mezquita de Dongguan, en Xining"]],
  r:[1,4]},
 {t:"Dunhuang y el corredor del Hexi",s:"Dos mil años de Ruta de la Seda en mil kilómetros de desierto",
  x:"Aquí no vienen occidentales. Es el tramo donde China se acababa y empezaba lo desconocido: caravanas, grutas budistas excavadas en acantilados, dunas de doscientos metros y los restos de la primera Gran Muralla, la de barro. Funciona en las dos temporadas: 28 grados en mayo, 33 secos y 6 mm de lluvia en todo agosto.",
  i:[["mogao_1","Grutas de Mogao: 492 cuevas talladas entre los siglos IV y XIV"],
     ["mogao_2","Los murales cubren 45.000 metros cuadrados"],
     ["mingsha_1","Lago de la Media Luna: un oasis que la arena no ha tragado en 2.000 años"],
     ["mingsha_2","Dunas de Mingsha, que suenan cuando sopla el viento"],
     ["yumen_1","Muralla Han en el paso de Yumen: barro, caña y 2.100 años"],
     ["yardang_1","Geoparque de Yardang: roca esculpida por el viento del Gobi"]],
  r:[1,3,4]},
 {t:"Zhangye y Jiayuguan",s:"Montañas de colores y el final oeste de la Muralla",
  x:"Zhangye son capas de arenisca teñidas de óxidos que solo funcionan con luz de atardecer. Jiayuguan es la fortaleza donde literalmente terminaba la Gran Muralla Ming y donde se desterraba a la gente.",
  i:[["zhangye_2","Danxia de Zhangye: 24 millones de años de sedimentos"],
     ["jiayuguan_1","La fortaleza de Jiayuguan sobre la llanura"],
     ["jiayuguan_2","El extremo occidental de la Muralla Ming"]],
  r:[1,3,4]},
 {t:"Guerreros de Terracota",s:"Lo que fuisteis a ver",
  x:"Ocho mil figuras a tamaño real, ninguna con la misma cara, enterradas durante 2.200 años hasta que unos campesinos cavaron un pozo en 1974. Xi'an además tiene una muralla de 14 km que se recorre entera en bici y un barrio musulmán que lleva mil años cocinando. En agosto, todo a primera hora: la ciudad llega a 40 grados.",
  i:[["terracota_2","La fosa 1 contiene unas 6.000 figuras"],
     ["terracota_1","Cada rostro es distinto, se cree que retratos reales"],
     ["xianwall_1","La muralla de Xi'an, 14 km de circuito cerrado"],
     ["xianfood_1","Biangbiang mian, cuyo carácter tiene 58 trazos"]],
  r:[1,2,3,4,5,6]},
 {t:"Gran Muralla salvaje",s:"Gubeikou y Jinshanling, no Badaling",
  x:"Badaling es una escalera mecánica con gente. Gubeikou y Jinshanling son 10 a 15 km de muralla sin restaurar donde crece la hierba entre las almenas y no hay tiendas de recuerdos. Se duerme al pie para ver el amanecer. En agosto se sale al alba y se lleva el doble de agua.",
  i:[["gubeikou_1","Gubeikou: muralla original, sin reconstruir"],
     ["jinshanling_2","Jinshanling recorriendo la cresta"],
     ["jinshanling_1","Al amanecer, antes de que llegue nadie"]],
  r:[1,2,3,4]},
 {t:"Pandas",s:"Dos opciones muy distintas",
  x:"Qinling, a 70 km de Xi'an, tiene 14 pandas de una subespecie diferente y al único panda marrón vivo del mundo. Casi nadie va, y cierra los lunes. Chengdú tiene doscientos y pico, incluidos bebés, y también dos horas de cola para ver tres minutos al panda estrella. En los dos sitios, hay que estar a las 7:30: después duermen.",
  i:[["panda_3","Qi Zai, el único panda pardo y blanco del mundo, en Qinling"],
     ["panda_1","Los pandas comen bambú 14 horas al día"],
     ["panda_2","La base de Chengdú: doscientos ejemplares y mucha gente"],
     ["leshan_1","El Buda de Leshan, 71 metros, a una hora de Chengdú"]],
  r:[1,4,6]},
 {t:"Zhangjiajie",s:"Las montañas de Avatar",
  x:"Más de 3.000 agujas de cuarcita de hasta 400 metros. Wulingyuan es el parque de los pilares y Tianmen es la montaña de al lado, con el teleférico más largo del mundo y un arco natural de 130 metros al que se sube por 999 escalones. En agosto llueve 18 días de media, pero la montaña está entre 5 y 10 grados más fresca que la ciudad y la niebla de después de la lluvia es cuando mejor se ve.",
  i:[["wulingyuan_1","Wulingyuan entre la niebla, que es como mejor se ve"],
     ["wulingyuan_2","Agujas de cuarcita de hasta 400 metros"],
     ["tianmen_2","La Puerta del Cielo, arco natural de 130 metros"],
     ["tianmen_1","Vista desde lo alto de Tianmen Shan"]],
  r:[2,3]},
 {t:"Minorías dong y miao",s:"Guizhou y Xiangxi, la China que no sale en las guías",
  x:"Aldeas de madera donde no se habla inglés ni chino mandarín en casa. Torres del tambor construidas sin un clavo, puentes del viento y la lluvia, y en Basha la única comunidad de China autorizada a llevar armas de fuego.",
  i:[["dong_1","Torre del tambor dong, ensamblada sin clavos"],
     ["zhaoxing_1","Traje y tocado de plata dong"],
     ["basha_1","Aldeas colgadas de las laderas de Guizhou"],
     ["furong_1","Furong, pueblo tujia construido sobre una cascada"],
     ["fenghuang_1","Fenghuang, casas sobre pilotes en el río Tuo"],
     ["jiabang_1","Terrazas de arroz talladas durante siglos"]],
  r:[2]},
 {t:"Los clásicos de Pekín y Shanghái",s:"Lo que sale en todas las guías, y sale por algo",
  x:"La Ciudad Prohibida son 9.000 estancias y 72 hectáreas, el mayor conjunto palaciego del mundo. Mutianyu es la Muralla cómoda, con teleférico y tobogán. El Bund enfrenta la banca colonial de los años veinte con los rascacielos de Pudong. Todo esto está lleno de gente, y aun así merece la pena verlo una vez.",
  i:[["gugong_2","Ciudad Prohibida: reserva obligatoria siete días antes, sin taquilla"],
     ["mutianyu_1","Mutianyu: restaurada, con teleférico y tobogán de bajada"],
     ["yiheyuan_1","Palacio de Verano: tres kilómetros cuadrados de lago cavados a mano"],
     ["bund_1","El Bund de Shanghái al anochecer"],
     ["suzhou_1","Los jardines clásicos de Suzhou"],
     ["hangzhou_1","El Lago del Oeste de Hangzhou"]],
  r:[5,6]},
 {t:"Huangshan y Yungang",s:"Los dos que solo entran en la versión larga",only:"Solo en agosto",
  x:"Las Montañas Amarillas son la montaña de la pintura clásica china: granito, pinos retorcidos y mar de nubes a 1.860 metros, entre 8 y 10 grados más fresco que Shanghái en pleno agosto. Las grutas de Yungang, en Datong, son 51.000 estatuas budistas talladas en arenisca en el siglo V, patrimonio de la Unesco y con una décima parte de gente que cualquier sitio de Pekín.",
  i:[["huangshan_1","Mar de nubes desde lo alto de Huangshan"],
     ["yungang_1","Yungang: 51.000 estatuas talladas en el siglo V"]],
  r:[5]},
 {t:"Guilin, Yangshuo y Longji",s:"Los karst del billete de 20 yuanes",
  x:"Torres de caliza de doscientos metros saliendo de campos de arroz. Es de lo más fotografiado de China y sigue siendo espectacular. Arriba, en Longji, hay laderas enteras esculpidas en terrazas desde hace 650 años: en mayo están inundadas y reflejan el cielo, en agosto están verdes y crecidas.",
  i:[["lijiang_1","El río Li entre los karst, la imagen del billete de 20 yuanes"],
     ["yangshuo_1","Yangshuo: torres de caliza y campos"],
     ["longji_1","Terrazas de Longji, talladas desde la dinastía Yuan"]],
  r:[6]},
 {t:"Pekín y Chengdú",s:"Los dos finales posibles",
  x:"Pekín no como circuito de monumentos sino como ciudad: el Templo del Cielo a las siete de la mañana no es un museo, es un parque donde los abuelos hacen tai chi y cantan ópera. Chengdú es el final blando, con casas de té, picante y el vuelo directo a Madrid.",
  i:[["tiantan_1","Templo del Cielo, a primera hora lleno de vecinos"],
     ["hutong_1","Los hutongs de Pekín"],
     ["chengdu_2","Jinli, en Chengdú"],
     ["crh_1","Los trenes que unen todo esto a 300 km/h"]],
  r:[1,2,3,4,5,6]}
];
