var ROUTES=[
{id:1,name:"La Ruta de la Seda",hex:"#D4541F",curve:.11,rec:true,
 sub:"El corredor del Hexi de punta a punta",
 may:{
  sub:"Shenzhen · Zhangye · Jiayuguan · Dunhuang · Xi'an · Pekín",
  pitch:"El corredor del Hexi de punta a punta. Veis la Gran Muralla en sus dos extremos opuestos, el fuerte del desierto y el dragón de montaña, con 2.500 km de por medio. Es la ruta con menos aeropuertos y la que casi ningún español ha hecho.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Qinling"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","lanzhou","avion",1900,"3 h 30"],["lanzhou","zhangye","tren",550,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","xian","avion",1620,"2 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegáis al amanecer. Huaqiangbei son 35 mercados especializados y más de 115.000 negocios apilados en manzanas enteras de componentes, drones y placas. Al lado, la estación de metro de Gangxia North parece una nave. Cena en Shekou."},
  {d:"Lun 3",t:"Shenzhen a fondo",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Robotaxi de nivel 4 con Pony.ai por Nanshan sin nadie al volante, DJI Sky City, reparto con dron de Meituan y tiendas de robots humanoides. Por la noche, vuelo al noroeste.",m:["avion","Vuelo nocturno a Lanzhou, 3 h 30"]},
  {d:"Mar 4",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, 24 millones de años de sedimentos",x:"Tren hasta Zhangye. Las montañas de Danxia son capas de arenisca teñidas de óxidos que solo revientan de color con la luz baja: hay que ir a última hora de la tarde, no a mediodía.",m:["tren","Lanzhou a Zhangye, 3 h"]},
  {d:"Mié 5",t:"Jiayuguan, donde acababa China",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo occidental de la Muralla Ming",x:"La fortaleza que cerraba el imperio por el oeste. Más allá empezaba lo desconocido. Se sube a la Muralla Colgante trepando por la ladera y se llega a la Primera Atalaya, asomada al cañón del río Taolai.",m:["tren","Zhangye a Jiayuguan, 1 h 30. Después a Dunhuang"]},
  {d:"Jue 6",t:"Mogao y las dunas",img:"mogao_1",cap:"Grutas de Mogao, 492 cuevas de los siglos IV al XIV",x:"Mogao por la mañana: el mayor archivo de arte budista del planeta, mil años de murales en cuevas cavadas en el acantilado. Por la tarde, las dunas de Mingsha y el lago de la Media Luna, un oasis que lleva dos mil años sin ser tragado por la arena."},
  {d:"Vie 7",t:"Desierto puro",img:"yumen_1",cap:"Muralla Han en el paso de Yumen, barro y caña, hace 2.100 años",x:"El día más raro del viaje. Paso de Yumen, los restos de la Muralla Han (mil años más antigua que la de las postales, hecha de capas de barro y caña, y sin nadie alrededor) y el geoparque de Yardang al atardecer.",m:["avion","Vuelo nocturno a Xi'an, 2 h 30"]},
  {d:"Sáb 8",t:"Guerreros de Terracota",img:"terracota_2",cap:"Fosa 1 del Mausoleo del Primer Emperador Qin",x:"Primer día limpio tras el Golden Week. Ocho mil figuras, ninguna con la misma cara, custodiando a un emperador que llevaba 2.200 años enterrado cuando unos campesinos cavaron un pozo en 1974. Por la tarde, la muralla de Xi'an en bici."},
  {d:"Dom 9",t:"El único panda marrón del mundo",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco vivo",x:"A 70 km de Xi'an está el centro de Qinling, con 14 pandas de una subespecie distinta de la de Sichuan. Allí vive Qi Zai, el único panda marrón del mundo. Casi no va ningún occidental. Por la tarde, tren a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Lun 10",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar con hierba entre las almenas",x:"De Gubeikou a Jinshanling: entre 10 y 15 km caminando por muralla sin restaurar, torres derruidas y ni una tienda de recuerdos. Se duerme en una casa rural al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mar 11",t:"Amanecer sobre la muralla",img:"jinshanling_1",cap:"Jinshanling al amanecer, medio restaurada y medio salvaje",x:"Por esto se duerme allí. Se sube de noche y se ve salir el sol sobre la cresta, sin nadie. Vuelta a Pekín, últimas horas y vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Xining · Qinghai · Zhangye · Jiayuguan · Dunhuang · Xi'an · Pekín",
  pitch:"La versión de agosto añade cuatro días y algo que en mayo no existe: el altiplano de Qinghai. Mientras Xi'an pasa de 38 grados, Xining se queda en 22 y el lago Qinghai está a 3.200 metros. Es la única ruta que en agosto mejora en lugar de empeorar.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Qinling","Altiplano de Qinghai"],
  no:["Sin Zhangjiajie","Sin minorías"],
  warnTitle:"Por qué esta es la ruta de agosto",
  warn:"Todas las demás rutas sufren el verano chino. Esta lo aprovecha: el corredor de Gansu tiene 33 grados de día, 18 de noche y 6 mm de lluvia en todo el mes, y el altiplano de Qinghai es directamente un refugio climático a 22 grados. Es donde se va la gente de Pekín y Shanghái a escapar del calor, y por una vez tienen razón.",
  legs:[["shenzhen","xining","avion",2200,"4 h"],["xining","qinghai","bus",150,"2 h 30"],["qinghai","chaka","bus",140,"2 h"],["xining","zhangye","tren",500,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","xian","avion",1620,"2 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, 35 mercados especializados de componentes, drones y placas, y la estación de metro de Gangxia North. Hará 33 grados y una humedad brutal: es el día de aclimatarse a lo peor antes de subir al altiplano."},
  {d:"Lun 16",t:"Shenzhen tecnológica",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Robotaxi de nivel 4 con Pony.ai por Nanshan, DJI Sky City, reparto con dron de Meituan y tiendas de robots humanoides. Por la noche, vuelo al altiplano.",m:["avion","Vuelo nocturno a Xining, 4 h"]},
  {d:"Mar 17",t:"Xining, 22 grados a 2.200 metros",img:"xining_1",cap:"Mezquita de Dongguan, uno de los grandes centros musulmanes del noroeste",x:"Bajáis de 33 grados con humedad a 22 grados secos. Xining es la puerta del Tíbet: mezquita de Dongguan, mercado nocturno de cordero y el monasterio de Kumbum a una hora. Día de aclimatación antes de subir a 3.200 metros."},
  {d:"Mié 18",t:"Lago Qinghai",img:"qinghai_1",cap:"El mayor lago salado de China, a 3.200 metros",x:"Cuatro veces el tamaño del lago de Ginebra, a 3.200 metros, con las montañas nevadas al fondo. Si venís en la ventana B (primera quincena) los campos de colza aún están en flor y la orilla es un mar amarillo.",m:["bus","Xining al lago Qinghai, 2 h 30"]},
  {d:"Jue 19",t:"Chaka, el espejo del cielo",img:"chaka_1",cap:"Chaka: costra de sal a 3.059 metros que refleja las nubes",x:"Un lago salado donde se camina sobre la costra blanca y el agua fina refleja el cielo entero. Vuelta a Xining por la noche.",m:["bus","Qinghai a Chaka y vuelta, 4 h"]},
  {d:"Vie 20",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, 24 millones de años de sedimentos",x:"Tren hacia el corredor del Hexi. Las franjas de arenisca teñidas de óxidos solo revientan de color con luz baja: hay que ir a última hora, nunca a mediodía.",m:["tren","Xining a Zhangye, 3 h"]},
  {d:"Sáb 21",t:"Jiayuguan, donde acababa China",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo occidental de la Muralla Ming",x:"La fortaleza que cerraba el imperio por el oeste. Muralla Colgante trepando la ladera y Primera Atalaya asomada al cañón del río Taolai. Tren a Dunhuang.",m:["tren","Zhangye a Jiayuguan 1 h 30, luego a Dunhuang"]},
  {d:"Dom 22",t:"Mogao y las dunas",img:"mogao_1",cap:"Grutas de Mogao, 492 cuevas de los siglos IV al XIV",x:"Las cuevas por la mañana, cuando aún no aprieta. Por la tarde las dunas de Mingsha y el lago de la Media Luna: en agosto el atardecer es a las 20:30, así que hay luz buena hasta tardísimo."},
  {d:"Lun 23",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, barro y caña de hace 2.100 años",x:"Día de desierto puro con 33 grados secos, que se llevan mucho mejor que los 33 húmedos de Shenzhen. El tramo de muralla más antiguo en pie y el geoparque de Yardang al atardecer.",m:["avion","Vuelo nocturno a Xi'an, 2 h 30"]},
  {d:"Mar 24",t:"Guerreros de Terracota",img:"terracota_2",cap:"Fosa 1 del Mausoleo del Primer Emperador Qin",x:"Xi'an en agosto pasa de 38 grados, así que los Guerreros a primera hora y la muralla en bici a última. Las horas centrales, museo o barrio musulmán a la sombra."},
  {d:"Mié 25",t:"El único panda marrón del mundo",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco vivo",x:"El centro de Qinling, a 70 km de Xi'an, con 14 pandas de una subespecie distinta y el único panda marrón del planeta. Está en montaña, así que se agradece. Cierra los lunes: hoy es miércoles.",m:["tren","Xi'an a Pekín por la tarde, 4 h 30"]},
  {d:"Jue 26",t:"Pekín viva",img:"tiantan_1",cap:"Templo del Cielo: a las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi y cantando ópera, hutongs de Gulou en bici y el 798 por la tarde. Agosto en Pekín son 32 grados y tormentas de tarde."},
  {d:"Vie 27",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"De Gubeikou a Jinshanling, entre 10 y 15 km por muralla sin restaurar. En agosto se sale al alba para evitar el calor y se lleva el doble de agua. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 28",t:"Amanecer sobre la muralla",img:"jinshanling_1",cap:"Jinshanling al amanecer, medio restaurada y medio salvaje",x:"Se sube de noche y se ve salir el sol sobre la cresta, sin nadie. Vuelta a Pekín, últimas horas y vuelo de madrugada."}]}},

{id:2,name:"La China del Sur",hex:"#1F7A4C",curve:.06,
 sub:"Aldeas dong y miao, Avatar y Terracota",
 may:{
  sub:"Shenzhen · Zhaoxing · Basha · Furong · Zhangjiajie · Xi'an · Pekín",
  pitch:"Aldeas dong y miao donde no se habla inglés, las montañas que inspiraron Avatar y los Guerreros. Casi todo va en tren de alta velocidad por el mismo corredor, sin volver atrás. Es la más auténtica en el sentido literal de la palabra.",
  yes:["Muralla","Terracota","Zhangjiajie","Minorías étnicas","Shenzhen"],
  no:["Sin Ruta de la Seda","Sin pandas"],
  legs:[["shenzhen","congjiang","tren",700,"3 h 30"],["congjiang","zhaoxing","bus",20,"25 min"],["zhaoxing","basha","bus",45,"1 h"],["basha","jishou","tren",400,"3 h"],["jishou","furong","tren",100,"40 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",900,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"De pueblo pesquero a 17 millones en cuarenta años",x:"Llegada al amanecer y día completo en Huaqiangbei y Nanshan. Es el contraste que da sentido al resto de la ruta: mañana estaréis en aldeas de madera sin ascensor."},
  {d:"Lun 3",t:"Shenzhen y salto a Guizhou",img:"shenzhen_2",cap:"Huaqiangbei, componentes y drones por manzanas enteras",x:"Mañana de tecnología: robotaxi, DJI, reparto con dron. Por la tarde, tren de alta velocidad a Congjiang y coche hasta Zhaoxing.",m:["tren","Shenzhen a Congjiang, 3 h 30"]},
  {d:"Mar 4",t:"Zhaoxing, la aldea dong",img:"dong_1",cap:"Torre del tambor dong, construida sin un solo clavo",x:"La mayor aldea dong de China: cinco torres del tambor, puentes del viento y la lluvia, y casas de madera apiladas en el valle. Caminata hasta Tang'an por las terrazas de arroz."},
  {d:"Mié 5",t:"Basha y las terrazas",img:"basha_1",cap:"Aldeas de Guizhou en las laderas",x:"Basha es la única comunidad de China autorizada a llevar armas de fuego. Los hombres se afeitan la cabeza con una hoz y llevan el moño tradicional. No es un espectáculo para turistas, es como viven."},
  {d:"Jue 6",t:"Furong, el pueblo sobre la cascada",img:"furong_1",cap:"Furong, pueblo tujia de 2.000 años sobre un salto de agua",x:"Tren hacia el norte, a Xiangxi. Furong lleva dos mil años ahí, literalmente construido encima de una cascada. Por la noche, a Zhangjiajie.",m:["tren","Congjiang a Jishou y Furong, 3 h 40"]},
  {d:"Vie 7",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares de arenisca de Wulingyuan entre la niebla",x:"Primer día tras el Golden Week, que es cuando las colas del ascensor Bailong se desinflan. Yuanjiajie y el pilar que rebautizaron como Hallelujah tras Avatar, y Tianzi Shan."},
  {d:"Sáb 8",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Más de 3.000 agujas de cuarcita de hasta 400 metros",x:"Yangjiajie, la parte salvaje: escaleras verticales talladas en la roca por donde no pasa ni la décima parte de la gente. Y el arroyo del Látigo Dorado por el fondo del cañón."},
  {d:"Dom 9",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, un arco natural de 130 metros",x:"El teleférico más largo del mundo, 7,5 km desde la propia ciudad. La carretera de las 99 curvas, los 999 escalones y las pasarelas de cristal clavadas en el acantilado.",m:["avion","Zhangjiajie a Xi'an, 2 h"]},
  {d:"Lun 10",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada guerrero tiene una cara distinta",x:"Día completo en Xi'an: los Guerreros por la mañana, la muralla en bici y el barrio musulmán al caer la tarde. Tren nocturno a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Mar 11",t:"Gran Muralla de Jinshanling",img:"jinshanling_2",cap:"Jinshanling, la sección más fotogénica y la menos concurrida",x:"Día completo en la muralla con el bus directo desde Dongzhimen. Vuelta a Pekín por la tarde y vuelo de madrugada.",m:["bus","Pekín a Jinshanling, 2 h"]}]},
 ago:{
  sub:"Shenzhen · Zhaoxing · Basha · Dehang · Fenghuang · Furong · Zhangjiajie · Xi'an · Pekín",
  pitch:"Con cuatro días más entran Dehang y Fenghuang, y Zhangjiajie deja de ser una carrera. El problema es el clima: es la ruta que peor lo pasa en agosto, con 18 días de lluvia de media en Zhangjiajie y humedad alta en Guizhou.",
  yes:["Muralla","Terracota","Zhangjiajie completo","Minorías étnicas","Shenzhen","Fenghuang y Dehang"],
  no:["Sin Ruta de la Seda","Sin pandas","La que peor lleva agosto"],
  warnTitle:"Esta es la ruta que más sufre en agosto",
  warn:"Zhangjiajie promedia <b>18 días de lluvia</b> en agosto y Guizhou va con humedad alta constante. Lo que juega a favor: la montaña de Wulingyuan está entre 5 y 10 grados más fresca que la ciudad, la niebla tras la lluvia es justamente cuando los pilares se ven mejor, y la segunda quincena llueve menos que la primera. Si elegís esta ruta en agosto, id a la ventana A y meted un día de colchón.",
  legs:[["shenzhen","congjiang","tren",700,"3 h 30"],["congjiang","zhaoxing","bus",20,"25 min"],["zhaoxing","basha","bus",45,"1 h"],["basha","jishou","tren",400,"3 h"],["jishou","fenghuang","bus",60,"1 h"],["jishou","furong","tren",100,"40 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",900,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"De pueblo pesquero a 17 millones en cuarenta años",x:"Llegada al amanecer. Huaqiangbei y Nanshan. Con 33 grados y humedad, el plan de agosto es interiores y noche: mercados con aire acondicionado de día y la bahía al anochecer."},
  {d:"Lun 16",t:"Shenzhen y salto a Guizhou",img:"shenzhen_2",cap:"Huaqiangbei, componentes y drones por manzanas enteras",x:"Mañana de robotaxi, DJI y reparto con dron. Por la tarde, tren a Congjiang y coche a Zhaoxing.",m:["tren","Shenzhen a Congjiang, 3 h 30"]},
  {d:"Mar 17",t:"Zhaoxing, la aldea dong",img:"dong_1",cap:"Torre del tambor dong, construida sin un solo clavo",x:"Cinco torres del tambor, puentes del viento y la lluvia, casas de madera apiladas. En agosto el arroz está verde y crecido, y por la noche refresca de verdad en el valle."},
  {d:"Mié 18",t:"Tang'an y las terrazas",img:"jiabang_1",cap:"Terrazas de arroz talladas durante siglos",x:"Caminata de Zhaoxing a Tang'an por las terrazas, hora y media subiendo. En agosto están en pleno verde. Se hace temprano, antes de que apriete."},
  {d:"Jue 19",t:"Basha Miao",img:"basha_1",cap:"Aldeas de Guizhou en las laderas",x:"La única comunidad de China autorizada a llevar armas de fuego. Los hombres se afeitan la cabeza con una hoz. No hay puesta en escena: es como viven."},
  {d:"Vie 20",t:"Dehang, cañón kárstico",img:"fenghuang_1",cap:"Xiangxi: aldeas miao entre paredes de caliza",x:"Tren al norte, a Xiangxi. Dehang es una aldea miao metida en un cañón de caliza con cascadas, y en agosto el agua es justamente lo que se agradece.",m:["tren","Congjiang a Jishou, 3 h"]},
  {d:"Sáb 21",t:"Fenghuang",img:"fenghuang_1",cap:"Casas sobre pilotes en el río Tuo",x:"El pueblo de casas sobre pilotes colgadas del río. Está muy turistificado, pero al amanecer y de noche con los faroles encendidos sigue mereciendo la pena.",m:["bus","Jishou a Fenghuang, 1 h"]},
  {d:"Dom 22",t:"Furong, el pueblo sobre la cascada",img:"furong_1",cap:"Furong, pueblo tujia de 2.000 años sobre un salto de agua",x:"Dos mil años construido literalmente encima de una cascada, que en agosto baja con todo el caudal del verano. Tren a Zhangjiajie.",m:["tren","Furong a Zhangjiajie, 30 min"]},
  {d:"Lun 23",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares de Wulingyuan entre la niebla",x:"Ascensor Bailong, Yuanjiajie y el pilar Hallelujah, Tianzi Shan. La niebla de después de la lluvia es exactamente cuando los pilares se ven como en las fotos."},
  {d:"Mar 24",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Más de 3.000 agujas de cuarcita de hasta 400 metros",x:"Yangjiajie, la parte salvaje de escaleras verticales por donde no pasa ni la décima parte de la gente, y el arroyo del Látigo Dorado por el fondo del cañón, que en agosto es la parte más fresca del parque."},
  {d:"Mié 25",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, arco natural de 130 metros",x:"Teleférico de 7,5 km desde la propia ciudad, carretera de las 99 curvas, 999 escalones y pasarelas de cristal en el acantilado."},
  {d:"Jue 26",t:"Gran Cañón y puente de cristal",img:"tianmen_1",cap:"Vista desde lo alto de Tianmen",x:"El día que solo cabe en la versión de agosto: el Gran Cañón de Zhangjiajie y el puente de cristal más largo del mundo, 430 metros a 300 de altura.",m:["avion","Vuelo nocturno a Xi'an, 2 h"]},
  {d:"Vie 27",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada guerrero tiene una cara distinta",x:"Guerreros a primera hora, que en agosto Xi'an llega a 38 grados. Muralla en bici al atardecer y barrio musulmán de noche.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Sáb 28",t:"Gran Muralla de Jinshanling",img:"jinshanling_2",cap:"Jinshanling, la más fotogénica y la menos concurrida",x:"Día completo en la muralla con el bus directo desde Dongzhimen, saliendo al alba. Vuelta a Pekín y vuelo de madrugada.",m:["bus","Pekín a Jinshanling, 2 h"]}]}},

{id:3,name:"El Gran Zigzag",hex:"#5B3DD1",curve:-.12,
 sub:"Máxima cobertura, máximo desgaste",
 may:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Xi'an · Zhangjiajie · Pekín",
  pitch:"Máxima cobertura: desierto, Terracota, Avatar y la Muralla dos veces. El precio son cinco vuelos internos y hacer la maleta seis veces en diez días. Con 32 años se aguanta, pero no es un viaje, es una campaña.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Zhangjiajie","Shenzhen"],
  no:["Sin minorías","Sin pandas","Cinco vuelos internos"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","xian","avion",1265,"2 h 30"],["xian","zhangjiajie","avion",900,"2 h"],["zhangjiajie","beijing","avion",1400,"2 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Llegada al amanecer. Huaqiangbei y la ciudad nueva."},
  {d:"Lun 3",t:"Shenzhen y salto al desierto",img:"shenzhen_3",cap:"Ping An Finance Center",x:"Robotaxi, DJI, drones de reparto. Por la noche, vuelo al otro extremo del país.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 4",t:"Mogao y Mingsha",img:"mingsha_1",cap:"El lago de la Media Luna entre las dunas de Mingsha",x:"Las grutas por la mañana y las dunas al atardecer, subiendo a pie o en camello."},
  {d:"Mié 5",t:"Yumen y Yardang",img:"yardang_1",cap:"Geoparque de Yardang, roca esculpida por el viento",x:"Paso de Yumen, la Muralla Han de hace 2.100 años y el desierto de yardangs. Tren a Jiayuguan.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Jue 6",t:"Jiayuguan",img:"jiayuguan_2",cap:"La fortaleza que cerraba el imperio por el oeste",x:"Fortaleza, Muralla Colgante y Primera Atalaya. Vuelo a Xi'an.",m:["avion","Jiayuguan a Xi'an, 2 h 30"]},
  {d:"Vie 7",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna repetida",x:"Primer día tras el festivo. Guerreros por la mañana y muralla en bici. Vuelo nocturno.",m:["avion","Xi'an a Zhangjiajie, 2 h"]},
  {d:"Sáb 8",t:"Wulingyuan",img:"wulingyuan_1",cap:"Los pilares que inspiraron Avatar",x:"Ascensor Bailong, Yuanjiajie, Tianzi Shan."},
  {d:"Dom 9",t:"Tianmen Shan",img:"tianmen_1",cap:"Vista desde lo alto de Tianmen",x:"Teleférico, 999 escalones y pasarelas de cristal. Vuelo nocturno a Pekín.",m:["avion","Zhangjiajie a Pekín, 2 h 30"]},
  {d:"Lun 10",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, sin restaurar",x:"Gubeikou a Jinshanling caminando. Se duerme en la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mar 11",t:"Amanecer y vuelta",img:"jinshanling_1",cap:"Amanecer en Jinshanling",x:"Sol saliendo sobre la cresta, vuelta a Pekín y vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Zhangye · Xi'an · Zhangjiajie · Pekín",
  pitch:"Con cuatro días más el Zigzag deja de ser una campaña militar: entra Zhangye, sobra un día en Xi'an y Zhangjiajie se hace en tres jornadas en vez de dos. Sigue siendo la ruta con más aviones, pero ya se puede respirar entre ellos.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Zhangjiajie completo","Shenzhen","Zhangye"],
  no:["Sin minorías","Sin pandas","Cuatro vuelos internos"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","zhangye","tren",220,"1 h 30"],["zhangye","xian","avion",1265,"2 h 30"],["xian","zhangjiajie","avion",900,"2 h"],["zhangjiajie","beijing","avion",1400,"2 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Llegada al amanecer. Huaqiangbei y la ciudad nueva, con 33 grados y humedad alta."},
  {d:"Lun 16",t:"Shenzhen tecnológica",img:"shenzhen_3",cap:"Ping An Finance Center",x:"Robotaxi, DJI Sky City, reparto con dron. Por la noche, vuelo al desierto.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 17",t:"Grutas de Mogao",img:"mogao_1",cap:"492 cuevas talladas entre los siglos IV y XIV",x:"El mayor archivo de arte budista del planeta. En verano la reserva es obligatoria y con cupo, así que va contratada de antemano."},
  {d:"Mié 18",t:"Mingsha y la Media Luna",img:"mingsha_1",cap:"El lago de la Media Luna entre las dunas",x:"Día tranquilo de dunas. En agosto anochece a las 20:30, así que se sube la duna a las siete de la tarde y todavía sobra luz."},
  {d:"Jue 19",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, barro y caña de hace 2.100 años",x:"El tramo de muralla más antiguo que sigue en pie y el geoparque de Yardang al atardecer. Tren a Jiayuguan.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Vie 20",t:"Jiayuguan",img:"jiayuguan_2",cap:"La fortaleza que cerraba el imperio por el oeste",x:"Fortaleza, Muralla Colgante trepando la ladera y Primera Atalaya sobre el cañón del Taolai.",m:["tren","Jiayuguan a Zhangye, 1 h 30"]},
  {d:"Sáb 21",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, capas de óxidos",x:"El día que no cabía en mayo. Danxia al atardecer, que es la única hora en que los colores funcionan de verdad.",m:["avion","Zhangye a Xi'an, 2 h 30"]},
  {d:"Dom 22",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna repetida",x:"A primera hora: Xi'an en agosto llega a 38 grados y las fosas son cubiertas pero sin aire acondicionado."},
  {d:"Lun 23",t:"Xi'an y vuelo a Hunan",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Muralla en bici al amanecer, museo por la tarde y barrio musulmán de noche. Vuelo a Zhangjiajie.",m:["avion","Xi'an a Zhangjiajie, 2 h"]},
  {d:"Mar 24",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares que inspiraron Avatar",x:"Ascensor Bailong, Yuanjiajie, Tianzi Shan. La montaña está entre 5 y 10 grados más fresca que la ciudad."},
  {d:"Mié 25",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Agujas de cuarcita de hasta 400 metros",x:"Yangjiajie y el arroyo del Látigo Dorado por el fondo del cañón, que es la parte fresca del parque."},
  {d:"Jue 26",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, arco natural de 130 metros",x:"Teleférico más largo del mundo, 99 curvas, 999 escalones y pasarelas de cristal.",m:["avion","Zhangjiajie a Pekín, 2 h 30"]},
  {d:"Vie 27",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, sin restaurar",x:"De Gubeikou a Jinshanling caminando, saliendo al alba por el calor. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 28",t:"Amanecer y vuelta",img:"jinshanling_1",cap:"Amanecer en Jinshanling",x:"Sol saliendo sobre la cresta, vuelta a Pekín y vuelo de madrugada."}]}},

{id:4,name:"Seda y Panda",hex:"#00747E",curve:-.19,
 sub:"Desierto, Muralla, Terracota y pandas",
 may:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Pekín · Xi'an · Chengdú",
  pitch:"El desierto, la Muralla, los Guerreros y los pandas de Chengdú, rematado con el vuelo directo Chengdú a Madrid. Es la ruta que mejor cierra: acabáis en Sichuan comiendo picante y salís sin volver sobre vuestros pasos.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Chengdú","Sichuan"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","beijing","avion",2000,"3 h 30"],["beijing","jinshanling","bus",130,"2 h"],["beijing","xian","tren",1200,"4 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","chengdu","tren",700,"3 h 10"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei",x:"Llegada al amanecer, Huaqiangbei y Gangxia North."},
  {d:"Lun 3",t:"Shenzhen y salto al desierto",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Robotaxi, DJI, drones. Vuelo nocturno a Dunhuang.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 4",t:"Mogao y las dunas",img:"mogao_2",cap:"Murales de Mogao, mil años de pintura budista",x:"Las 492 cuevas por la mañana, las dunas de Mingsha y el lago de la Media Luna al atardecer."},
  {d:"Mié 5",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, hace 2.100 años",x:"Día de desierto puro, el tramo de muralla más antiguo en pie y el geoparque de Yardang. Tren a Jiayuguan.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Jue 6",t:"Jiayuguan y salto a Pekín",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan",x:"La fortaleza del extremo oeste, la Muralla Colgante y la Primera Atalaya. Vuelo a Pekín.",m:["avion","Jiayuguan a Pekín, 3 h 30"]},
  {d:"Vie 7",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"Primer día tras el festivo, perfecto para la muralla. De Gubeikou a Jinshanling caminando. Se duerme allí.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 8",t:"Amanecer en la muralla y Pekín",img:"tiantan_1",cap:"Templo del Cielo, a las siete de la mañana es un parque vivo",x:"Amanecer en Jinshanling, vuelta a Pekín y tarde por los hutongs. Tren nocturno a Xi'an.",m:["tren","Pekín a Xi'an, 4 h 30"]},
  {d:"Dom 9",t:"Guerreros de Terracota",img:"terracota_1",cap:"Ninguna figura repite rostro",x:"Guerreros por la mañana, muralla en bici por la tarde y barrio musulmán al anochecer."},
  {d:"Lun 10",t:"Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Tren rápido a Sichuan. Tarde de casas de té, Jinli y hotpot sichuanés, que es un rito social de tres horas.",m:["tren","Xi'an a Chengdú, 3 h 10"]},
  {d:"Mar 11",t:"Pandas al amanecer",img:"panda_1",cap:"Los pandas están activos de 7:30 a 10:00, después duermen",x:"A la base de cría a primera hora, la única franja en que los pandas hacen algo. Por la noche, vuelo directo Chengdú a Madrid.",m:["avion","Chengdú a Madrid, directo 12 h 20"]}]},
 ago:{
  sub:"Shenzhen · Xining · Qinghai · Zhangye · Jiayuguan · Dunhuang · Pekín · Xi'an · Chengdú",
  pitch:"La versión larga mete el altiplano de Qinghai al principio y el Buda de Leshan al final, y añade los pandas de Qinling además de los de Chengdú. Empieza a 3.200 metros y acaba comiendo picante en Sichuan, saliendo por el directo a Madrid.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas, dos veces","Qinghai","Leshan"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","xining","avion",2200,"4 h"],["xining","qinghai","bus",150,"2 h 30"],["xining","zhangye","tren",500,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","beijing","avion",2300,"4 h"],["beijing","jinshanling","bus",130,"2 h"],["beijing","xian","tren",1200,"4 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","chengdu","tren",700,"3 h 10"],["chengdu","leshan","tren",130,"1 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei",x:"Llegada al amanecer. Huaqiangbei y Gangxia North, con calor húmedo de 33 grados."},
  {d:"Lun 16",t:"Shenzhen y salto al altiplano",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Robotaxi, DJI, drones de reparto. Vuelo nocturno a Xining, del calor húmedo a 22 grados secos.",m:["avion","Shenzhen a Xining, 4 h"]},
  {d:"Mar 17",t:"Xining y lago Qinghai",img:"qinghai_1",cap:"El mayor lago salado de China, a 3.200 metros",x:"Mezquita de Dongguan por la mañana y por la tarde al lago, cuatro veces el tamaño del lago de Ginebra con las montañas nevadas detrás.",m:["bus","Xining al lago Qinghai, 2 h 30"]},
  {d:"Mié 18",t:"Chaka, el espejo del cielo",img:"chaka_1",cap:"Costra de sal a 3.059 metros que refleja las nubes",x:"Se camina sobre la costra blanca y la lámina de agua refleja el cielo entero. Vuelta a Xining y tren al corredor del Hexi.",m:["tren","Xining a Zhangye, 3 h"]},
  {d:"Jue 19",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, capas de óxidos",x:"Danxia al atardecer, la única hora en que los colores funcionan. Tren a Jiayuguan.",m:["tren","Zhangye a Jiayuguan, 1 h 30"]},
  {d:"Vie 20",t:"Jiayuguan",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo oeste de la Muralla Ming",x:"Fortaleza, Muralla Colgante y Primera Atalaya sobre el cañón del Taolai. Tren a Dunhuang.",m:["tren","Jiayuguan a Dunhuang, 2-3 h"]},
  {d:"Sáb 21",t:"Mogao y las dunas",img:"mogao_2",cap:"Murales de Mogao, mil años de pintura budista",x:"Las 492 cuevas por la mañana y las dunas de Mingsha con el lago de la Media Luna al atardecer."},
  {d:"Dom 22",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, hace 2.100 años",x:"Desierto puro: el tramo de muralla más antiguo en pie y el geoparque de Yardang. Vuelo nocturno a Pekín.",m:["avion","Dunhuang a Pekín, 4 h"]},
  {d:"Lun 23",t:"Pekín viva",img:"tiantan_1",cap:"Templo del Cielo, a las siete de la mañana es un parque vivo",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi, hutongs de Gulou en bici y 798 por la tarde."},
  {d:"Mar 24",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"De Gubeikou a Jinshanling caminando, saliendo al alba. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mié 25",t:"Amanecer y tren a Xi'an",img:"jinshanling_1",cap:"Jinshanling al amanecer",x:"Sol saliendo sobre la cresta sin nadie, vuelta a Pekín y tren rápido a Xi'an.",m:["tren","Pekín a Xi'an, 4 h 30"]},
  {d:"Jue 26",t:"Terracota y pandas de Qinling",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco del mundo",x:"Los Guerreros a primera hora y por la tarde el centro de Qinling, a 70 km, con el único panda marrón vivo. Cierra los lunes: hoy es jueves.",m:["bus","Xi'an a Qinling, 1 h 30"]},
  {d:"Vie 27",t:"Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Tren a Sichuan. Casas de té en el parque del Pueblo, donde los jubilados juegan al mahjong, y hotpot por la noche.",m:["tren","Xi'an a Chengdú, 3 h 10"]},
  {d:"Sáb 28",t:"Pandas y el Buda de Leshan",img:"leshan_1",cap:"El Buda de Leshan, 71 metros tallados en el acantilado",x:"Pandas a las 7:30, la única franja en que están despiertos, y por la tarde el Buda gigante de Leshan, a una hora en tren: 71 metros excavados en la roca en el siglo VIII. Vuelo directo a Madrid de madrugada.",m:["avion","Chengdú a Madrid, directo 12 h 20"]}]}},

{id:5,name:"El Triángulo Clásico",hex:"#C2185B",curve:.13,classic:true,
 sub:"El primer viaje a China de toda la vida",
 may:{
  sub:"Shanghái · Suzhou · Hangzhou · Xi'an · Pekín",
  pitch:"El primer viaje a China de toda la vida: Shanghái, los Guerreros, la Ciudad Prohibida y la Muralla. Es el circuito que hace todo el mundo, y por algo es. El aviso es serio: también es el que peor encaja con vuestras fechas.",
  yes:["Muralla en Mutianyu","Terracota","Ciudad Prohibida","Shanghái","Todo en tren"],
  no:["Sin Shenzhen","Sin desierto","Sin naturaleza","El más masificado"],
  legs:[["shanghai","suzhou","tren",100,"30 min"],["shanghai","hangzhou","tren",170,"1 h"],["shanghai","xian","tren",1500,"6 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shanghái",img:"bund_1",cap:"El Bund, fachada colonial a un lado del río y Pudong al otro",x:"Llegada al amanecer en vuelo directo desde Barcelona o Madrid. El Bund al atardecer es el contraste que define la ciudad. Cena en la antigua concesión francesa."},
  {d:"Lun 3",t:"Shanghái entera",img:"shanghai_1",cap:"Pudong: en 1990 esto eran campos de arroz",x:"Pudong, el Museo de Shanghái y Tianzifang. Shanghái aguanta bien el Golden Week porque es enorme y no depende de un solo monumento con aforo."},
  {d:"Mar 4",t:"Suzhou, los jardines",img:"suzhou_1",cap:"Jardín del Administrador Humilde, patrimonio de la Unesco",x:"Media hora de tren. Suzhou conserva los mejores jardines clásicos chinos, paisajes en miniatura diseñados entre los siglos XI y XIX.",m:["tren","Shanghái a Suzhou, 30 min"]},
  {d:"Mié 5",t:"Hangzhou y el Lago del Oeste",img:"hangzhou_1",cap:"El Lago del Oeste, mil años de jardín construido",x:"El lago que los poetas chinos llevan un milenio describiendo, con diques, pagodas e islas artificiales.",m:["tren","Shanghái a Hangzhou, 1 h"]},
  {d:"Jue 6",t:"Tren a Xi'an",img:"crh_1",cap:"Seis horas a 300 km/h cruzando China",x:"Día de traslado, lo mejor que se puede hacer el último día del festivo. Por la tarde, el barrio musulmán de Xi'an.",m:["tren","Shanghái a Xi'an, 6 h"]},
  {d:"Vie 7",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna con la misma cara",x:"Primer día limpio tras el Golden Week, por eso la ruta va en este orden y no al revés. Por la tarde, la muralla de Xi'an en bici."},
  {d:"Sáb 8",t:"Tren a Pekín",img:"tiantan_1",cap:"Templo del Cielo: a las siete de la mañana es un parque de barrio",x:"Cuatro horas y media de tren. Por la tarde, el Templo del Cielo y los hutongs de Gulou en bici.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Dom 9",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Desde 2026 no se venden entradas en taquilla. Hay que reservar online con pasaporte, el cupo es de 40.000 al día y se abre solo siete días antes a las 20:00 hora de Pekín."},
  {d:"Lun 10",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: restaurada, con teleférico y tobogán de bajada",x:"La versión cómoda de la Muralla. Más gente que en Gubeikou, pero se llega en hora y media y no hay que caminar quince kilómetros.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Mar 11",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"El jardín imperial donde la corte huía del calor: tres kilómetros cuadrados de lago artificial cavados a mano. Vuelo de madrugada."}]},
 ago:{
  sub:"Shanghái · Suzhou · Hangzhou · Huangshan · Xi'an · Pekín · Datong",
  pitch:"Con cuatro días más el clásico gana dos cosas que lo mejoran mucho en verano: las Montañas Amarillas, que a 1.860 metros son el refugio climático del este de China, y las grutas de Yungang en Datong, patrimonio de la Unesco y muy poco visitadas por extranjeros.",
  yes:["Muralla en Mutianyu","Terracota","Ciudad Prohibida","Shanghái","Huangshan","Grutas de Yungang"],
  no:["Sin Shenzhen","Sin desierto","El más masificado"],
  warnTitle:"El clásico en agosto: calor y colas a la vez",
  warn:"Shanghái en agosto pasa de 35 grados con humedad altísima y es temporada de tifones. Xi'an llega a 40. Y las vacaciones escolares chinas llenan justamente estos sitios durante todo el mes. Lo que salva la versión de agosto es Huangshan: a 1.860 metros se está entre 8 y 10 grados más fresco, y es donde se refugia medio Shanghái.",
  legs:[["shanghai","suzhou","tren",100,"30 min"],["shanghai","hangzhou","tren",170,"1 h"],["hangzhou","huangshan","tren",280,"1 h 30"],["huangshan","xian","avion",1000,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"],["beijing","datong","tren",290,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shanghái",img:"bund_1",cap:"El Bund, fachada colonial a un lado y Pudong al otro",x:"Llegada al amanecer en directo desde Barcelona o Madrid. El Bund al anochecer, que en agosto es cuando se puede estar en la calle."},
  {d:"Lun 16",t:"Shanghái entera",img:"shanghai_1",cap:"Pudong: en 1990 esto eran campos de arroz",x:"Pudong y el Museo de Shanghái por la mañana, Tianzifang y la concesión francesa al caer la tarde. Con 35 grados y humedad, el plan es museo a mediodía y calle de noche."},
  {d:"Mar 17",t:"Suzhou, los jardines",img:"suzhou_1",cap:"Jardín del Administrador Humilde, patrimonio de la Unesco",x:"Media hora de tren. Los mejores jardines clásicos chinos, pensados justamente como refugio de sombra y agua para el verano.",m:["tren","Shanghái a Suzhou, 30 min"]},
  {d:"Mié 18",t:"Hangzhou y el Lago del Oeste",img:"hangzhou_1",cap:"El Lago del Oeste, mil años de jardín construido",x:"Diques, pagodas e islas artificiales. En agosto los lotos están en flor, que es la estampa clásica del lago.",m:["tren","Shanghái a Hangzhou, 1 h"]},
  {d:"Jue 19",t:"Subida a Huangshan",img:"huangshan_1",cap:"Mar de nubes desde lo alto de las Montañas Amarillas",x:"Hora y media de tren y se sube a 1.860 metros. Es la montaña que sale en toda la pintura clásica china: pinos retorcidos, granito y mar de nubes. Se duerme arriba.",m:["tren","Hangzhou a Huangshan, 1 h 30"]},
  {d:"Vie 20",t:"Amanecer sobre el mar de nubes",img:"huangshan_1",cap:"Los pinos de Huangshan sobre el granito",x:"Amanecer desde la cumbre, que es la razón de dormir arriba, y bajada por la otra vertiente. Ocho o diez grados menos que en Shanghái.",m:["avion","Huangshan a Xi'an, 2 h"]},
  {d:"Sáb 21",t:"Xi'an, muralla y barrio musulmán",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Muralla en bici al amanecer, 14 km de circuito cerrado, y barrio musulmán de noche. Las horas centrales, a la sombra."},
  {d:"Dom 22",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna con la misma cara",x:"A primera hora sí o sí: en agosto Xi'an llega a 40 grados y las fosas están cubiertas pero sin climatizar.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Lun 23",t:"Pekín, Templo del Cielo",img:"tiantan_1",cap:"A las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi y cantando ópera, y hutongs de Gulou en bici."},
  {d:"Mar 24",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Reserva obligatoria con pasaporte siete días antes, cupo de 40.000 y sin taquilla. En agosto se agota en minutos. Sin sombra dentro: entrada a primera hora."},
  {d:"Mié 25",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: teleférico de subida y tobogán de bajada",x:"La Muralla cómoda, a hora y media de Pekín. En agosto se va al abrir y se baja antes de mediodía.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Jue 26",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"Precisamente el sitio donde la corte imperial huía del calor de Pekín: tres kilómetros cuadrados de lago artificial y galerías cubiertas."},
  {d:"Vie 27",t:"Datong y las grutas de Yungang",img:"yungang_1",cap:"Yungang: 51.000 estatuas budistas talladas en el siglo V",x:"Dos horas de tren al oeste. Cincuenta y una mil estatuas excavadas en arenisca en el siglo V, patrimonio de la Unesco y con una décima parte de la gente que hay en Pekín.",m:["tren","Pekín a Datong, 2 h"]},
  {d:"Sáb 28",t:"Monasterio Colgante y vuelta",img:"yungang_1",cap:"Las grutas de Yungang, en Datong",x:"El Monasterio Colgante de Hengshan, encajado en la pared de un barranco desde hace 1.500 años, y vuelta a Pekín para el vuelo de madrugada.",m:["tren","Datong a Pekín, 2 h"]}]}},

{id:6,name:"El Clásico Ampliado",hex:"#2F4858",curve:-.07,classic:true,
 sub:"El circuito de dos semanas de las agencias",
 may:{
  sub:"Shenzhen · Yangshuo · Longji · Chengdú · Xi'an · Pekín",
  pitch:"El circuito clásico completo, el de dos semanas de las agencias, comprimido en diez días: tecnología, los karst de Guilin, las terrazas de arroz, los pandas, los Guerreros y la Muralla. Es el que más cosas distintas mete sin salirse de lo conocido.",
  yes:["Muralla en Mutianyu","Terracota","Pandas de Chengdú","Shenzhen","Karst de Guilin","Minorías zhuang y yao"],
  no:["Sin desierto","Sin Zhangjiajie","Todo muy visitado"],
  legs:[["shenzhen","guilin","tren",700,"2 h 40"],["guilin","yangshuo","bus",65,"1 h 15"],["guilin","longji","bus",100,"2 h"],["guilin","chengdu","avion",1100,"1 h 45"],["chengdu","xian","tren",700,"3 h 10"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, robotaxi por Nanshan y Gangxia North. Un día en la China de 2027 antes de irse a la China de postal."},
  {d:"Lun 3",t:"Tren a Guilin y Yangshuo",img:"yangshuo_1",cap:"Los karst de Yangshuo saliendo de los campos de arroz",x:"Menos de tres horas de tren y cambia el país entero: torres de caliza de doscientos metros brotando de los campos.",m:["tren","Shenzhen a Guilin, 2 h 40"]},
  {d:"Mar 4",t:"Río Li en balsa de bambú",img:"lijiang_1",cap:"El paisaje que sale en el billete de 20 yuanes",x:"Bajar el río Li en balsa entre los karst es literalmente la imagen del billete de 20 yuanes. Por la tarde, bici por el campo entre pueblos."},
  {d:"Mié 5",t:"Terrazas de Longji",img:"longji_1",cap:"Terrazas talladas hace 650 años por los zhuang y los yao",x:"Dos horas al norte. Una ladera entera esculpida en terrazas desde la dinastía Yuan. En mayo están inundadas y reflejan el cielo.",m:["bus","Guilin a Longji, 2 h"]},
  {d:"Jue 6",t:"Vuelo a Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Hora y tres cuartos de vuelo. Tarde de casas de té en el parque del Pueblo y hotpot sichuanés por la noche.",m:["avion","Guilin a Chengdú, 1 h 45"]},
  {d:"Vie 7",t:"Pandas al amanecer",img:"panda_2",cap:"La base de cría de Chengdú, doscientos y pico ejemplares",x:"A la base a las 7:30, la única franja en la que los pandas están despiertos y comiendo. A partir de las diez se duermen y llega el grueso de la gente."},
  {d:"Sáb 8",t:"Tren a Xi'an",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter chino tiene 58 trazos",x:"Tres horas de tren atravesando las montañas Qinling por túnel. Tarde de muralla en bici y noche en el barrio musulmán.",m:["tren","Chengdú a Xi'an, 3 h 10"]},
  {d:"Dom 9",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada rostro es distinto, se cree que retratos reales",x:"Ocho mil figuras enterradas 2.200 años hasta que unos campesinos cavaron un pozo en 1974. Tren nocturno a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Lun 10",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu, la sección restaurada más manejable",x:"Teleférico para subir, tobogán para bajar y hora y media desde Pekín.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Mar 11",t:"Ciudad Prohibida y Templo del Cielo",img:"gugong_2",cap:"La entrada a la Ciudad Prohibida",x:"Reserva obligatoria con pasaporte, siete días antes y sin taquilla. Por la tarde el Templo del Cielo y los hutongs. Vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Yangshuo · Longji · Chengdú · Leshan · Xi'an · Pekín",
  pitch:"El clásico ampliado con los cuatro días que le faltaban: dos jornadas de verdad en Yangshuo, el Buda gigante de Leshan y un día extra en Pekín. En agosto las terrazas de Longji están verdes y crecidas, que para muchos es mejor foto que inundadas.",
  yes:["Muralla en Mutianyu","Terracota","Pandas de Chengdú","Shenzhen","Karst de Guilin","Longji","Buda de Leshan"],
  no:["Sin desierto","Sin Zhangjiajie","Tifones en el tramo sur"],
  warnTitle:"Ojo al tramo sur en agosto",
  warn:"Shenzhen, Guilin y Yangshuo están de lleno en la zona de tifones, con 4 a 6 de media en agosto y cancelaciones habituales de vuelos y trenes. Como ese tramo va al principio, un tifón os come días de karst pero no os hace perder el vuelo internacional, que sale de Pekín. Aun así, seguro con cobertura de cancelación.",
  legs:[["shenzhen","guilin","tren",700,"2 h 40"],["guilin","yangshuo","bus",65,"1 h 15"],["guilin","longji","bus",100,"2 h"],["guilin","chengdu","avion",1100,"1 h 45"],["chengdu","leshan","tren",130,"1 h"],["chengdu","xian","tren",700,"3 h 10"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, robotaxi por Nanshan y Gangxia North. Un día en la China de 2027 antes de irse a la de postal."},
  {d:"Lun 16",t:"Shenzhen y tren a Guilin",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Mañana de DJI Sky City y reparto con dron. Por la tarde, menos de tres horas de tren y cambia el país entero.",m:["tren","Shenzhen a Guilin, 2 h 40"]},
  {d:"Mar 17",t:"Río Li en balsa de bambú",img:"lijiang_1",cap:"El paisaje que sale en el billete de 20 yuanes",x:"Bajar el río entre torres de caliza de doscientos metros. En agosto el río va crecido y verde, y hay que salir temprano por el calor."},
  {d:"Mié 18",t:"Yangshuo en bici",img:"yangshuo_1",cap:"Karst y campos de arroz alrededor de Yangshuo",x:"El día que no cabe en la versión de mayo: bici por el campo entre pueblos, la cueva de agua y el circuito de Yulong. Es como mejor se ve la zona."},
  {d:"Jue 19",t:"Terrazas de Longji",img:"longji_1",cap:"Terrazas talladas hace 650 años por los zhuang y los yao",x:"Dos horas al norte. En agosto están verdes y crecidas, con las aldeas zhuang y yao arriba del todo. Se duerme en la montaña, que refresca.",m:["bus","Guilin a Longji, 2 h"]},
  {d:"Vie 20",t:"Vuelo a Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Hora y tres cuartos de vuelo. Casas de té en el parque del Pueblo, donde los jubilados juegan al mahjong, y hotpot por la noche.",m:["avion","Guilin a Chengdú, 1 h 45"]},
  {d:"Sáb 21",t:"Pandas al amanecer",img:"panda_2",cap:"La base de cría de Chengdú, doscientos y pico ejemplares",x:"A la base a las 7:30, la única franja en la que están despiertos. A partir de las diez se duermen y llega el grueso de la gente."},
  {d:"Dom 22",t:"El Buda gigante de Leshan",img:"leshan_1",cap:"71 metros tallados en el acantilado en el siglo VIII",x:"Una hora de tren. El Buda de piedra más grande del mundo, excavado en el acantilado durante noventa años en el siglo VIII. Se ve desde barco y desde la escalera lateral.",m:["tren","Chengdú a Leshan, 1 h"]},
  {d:"Lun 23",t:"Tren a Xi'an",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Tres horas atravesando las montañas Qinling por túnel. Muralla en bici al atardecer y barrio musulmán de noche.",m:["tren","Chengdú a Xi'an, 3 h 10"]},
  {d:"Mar 24",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada rostro es distinto, se cree que retratos reales",x:"A primera hora: en agosto Xi'an llega a 40 grados. Ocho mil figuras enterradas 2.200 años hasta 1974.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Mié 25",t:"Pekín, Templo del Cielo y hutongs",img:"tiantan_1",cap:"A las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con tai chi y ópera, hutongs de Gulou en bici y el 798 por la tarde."},
  {d:"Jue 26",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Reserva con pasaporte siete días antes, cupo de 40.000 y sin taquilla. Entrada a primera hora, que dentro no hay sombra."},
  {d:"Vie 27",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: teleférico de subida y tobogán de bajada",x:"La Muralla cómoda, hora y media desde Pekín. Al abrir y de vuelta antes de mediodía.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Sáb 28",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"El jardín donde la corte huía del calor de Pekín, que en agosto se entiende perfectamente. Vuelo de madrugada."}]}}
];
