var ROUTES=[
{id:1,name:"La ruta probada",hex:"#C53026",hexm:"#FF8E78",curve:.08,real:true,
 sub:"Los diez destinos de un viaje real, adaptados a vuestras fechas",
 extra:'<h3 class="xh">Lo que este itinerario trae aprendido</h3>'+
  '<p class="xlede">La ruta nace de un viaje real de 22 noches por estos mismos diez destinos, planificado tramo a tramo contra la venta real de billetes durante meses. Estos avisos costaron horas descubrirlos y aquí vienen de serie.</p>'+
  '<div class="xgrid">'+
  '<div class="xcard"><h4>Las estaciones trampa</h4><p>Chongqing tiene <b>cuatro</b> estaciones: se llega a Chongqing Norte y se sale hacia Fenghuang desde Chongqing Este, a 21 km. En Pekín los trenes buenos salen de Beijingxi (oeste), pero en la misma búsqueda aparecen otros desde Fengtai y Qinghe que no lo son. En Shanghái es Hongqiao, y salen a horas parecidas trenes a Shanghai Sur. Y la estación de Furong se escribe todo junto: Furongzhen.</p></div>'+
  '<div class="xcard"><h4>El horario general miente</h4><p>Un tren puede existir en el horario general y no circular vuestro día concreto: en el viaje original pasó dos veces. Solo vale el listado real de la fecha, que se abre 15 días antes. Y el buscador por ruta de Ctrip devuelve cero trenes hacia Fenghuang Gucheng por un fallo suyo, no porque no haya: se comprueba en Trip.com.</p></div>'+
  '<div class="xcard"><h4>Los ramales sin mañanas</h4><p>Entre Fenghuang, Furong y Zhangjiajie hay fechas en que el primer tren del día sale a las 11:29 o directamente por la tarde. Si al buscar solo salen trenes tardíos, primero quitad los filtros (el botón lleva un globo naranja con el número de filtros activos), y si siguen sin salir es que no existen: se resuelve con coche con chófer, encargado en recepción la noche antes y con precio cerrado. En el Xiangxi rural Didi no es fiable.</p></div>'+
  '<div class="xcard"><h4>Los tramos críticos</h4><p>Zhangjiajie Oeste a Shangrao: cuatro directos al día, unas seis horas pasando por Changsha Sur sin transbordo. Chongqing Este a Fenghuang: tres. Esos billetes se compran en el primer minuto de la venta; la hora exacta a la que abre cada estación la da la app 12306 (Me, guía de viaje, hora de salida a la venta). Plan B si se agotan: transbordo en Changsha Sur, que tiene 46 trenes al día hacia Shangrao.</p></div>'+
  '<div class="xcard"><h4>La regla de la hora</h4><p>En la estación una hora antes de la salida, siempre: las estaciones chinas son aeropuertos, con control de pasaporte, escáner y andenes a un cuarto de hora andando. El desayuno que no dé tiempo a tomar se pide para llevar la noche antes en recepción: 打包早餐 (da bao zao can). Funciona en todos los hoteles de esta lista.</p></div>'+
  '<div class="xcard"><h4>Tianmen y su teleférico</h4><p>El tramo superior del teleférico está en obras desde finales de 2025 y no se espera hasta bien entrado 2027: se sube con el teleférico corto, bus por las 99 curvas y siete tramos de escaleras mecánicas. Confirmad el estado real antes de comprar. Los visitantes de día bajan antes de las 18:00: el espectáculo de luces (18:30 a 21:00) pide tour nocturno o dormir en el hotel de la montaña.</p></div>'+
  '<div class="xcard"><h4>Reservas con nombre y ventana</h4><p>Ciudad Prohibida: sin taquilla, cupo de 40.000, la venta abre 7 días antes a las 20:00 de China (las 14:00 en España) y cierra los lunes. La plaza de Tiananmen tiene reserva propia, gratuita, en un mini programa de WeChat y con franjas: la bajada de bandera es una franja concreta. Sin ella no se cruza la plaza ni de paso. Todo se entra escaneando el pasaporte físico.</p></div>'+
  '<div class="xcard"><h4>Terracota a las 13:00</h4><p>El consejo de las guías locales: entrar a partir de las 13:00 y hacer los fosos en orden inverso, 3, 2 y 1, a contracorriente de los tours de la mañana. El carrito eléctrico del jardín Lishan (15 yuanes) ahorra 2,5 km a pie. Y al terminar los fosos queda la mitad de la visita: el bus gratuito lleva a los Carruajes de Bronce.</p></div>'+
  '<div class="xcard"><h4>Zhangjiajie, dinero y colas</h4><p>La entrada del parque (236 yuanes) vale cuatro días e incluye los buses internos, pero no el ascensor Bailong (65) ni los teleféricos (72 a 76): el día completo sale por unos 373 yuanes, unos 48 euros. Si la cola del Bailong pasa de una hora, girad el día: arriba por el teleférico de Tianzi y el Bailong para bajar a partir de las 16:00.</p></div>'+
  '<div class="xcard"><h4>Las luces tienen horario</h4><p>Casi todo lo bonito de esta ruta pasa de noche, y cada sitio apaga a su hora: Wangxian se enciende a las 19:45 y aguanta hasta las 23:00; la cascada de Furong y Hongyadong, hasta las 23:00; el espectáculo de Tianmen va de 18:30 a 21:00; y en Fenghuang los bares del río meten música hasta pasadas las 23:00, así que se pide habitación al río pero lejos del tramo de bares.</p></div>'+
  '<div class="xcard"><h4>Hongyadong se mira desde fuera</h4><p>El edificio de trece pisos apilados es gratis y se ve mejor desde el puente Qiansimen que desde dentro. Se enciende al anochecer y aguanta hasta las 23:00. En verano id después de cenar, que a las 20:00 la ciudad todavía es un horno.</p></div>'+
  '<div class="xcard"><h4>Mutianyu, torre 6</h4><p>El tobogán de 1.580 metros baja desde la torre 6, y a esa torre sube la telesilla: el combo correcto es telesilla más tobogán (140 yuanes). El teleférico de cabina sube a la torre 14 y ahí no hay tobogán. Con lluvia el tobogán no abre, así que si el cielo amenaza, cambiad el día de Muralla por el de ciudad.</p></div>'+
  '<div class="xcard"><h4>El desayuno importa más de lo que parece</h4><p>Al reservar hotel, mirad a qué hora abre el desayuno antes que el precio: un bufé que abre a las 07:30 choca con los pandas, con los parques y con la mitad de los trenes de la mañana. Los dos hoteles que mejor funcionaron del viaje original abrían a las 06:30.</p></div>'+
  '</div>'+
  '<h3 class="xh" style="margin-top:34px">Los pueblos con entrada, y dónde dormir para las luces</h3>'+
  '<p class="xlede">Tres pueblos de esta ruta se viven de noche, y en dos de ellos se paga por entrar: por eso en el viaje original se dormía dentro. Así funciona cada uno, y debajo van los alojamientos con mejores vistas nocturnas que señalan los blogs de viajeros, comprobados uno a uno en Booking (nota y reseñas de agosto de 2026).</p>'+
  '<div class="xgrid xg3">'+
  '<div class="xcard"><h4>Fenghuang: pasear es gratis</h4><p>El casco antiguo es de acceso libre las 24 horas desde 2016; lo que se paga es el combinado de atracciones (unos 148 yuanes, o 208 con el barco por el Tuojiang, válido 48 horas). Dormir dentro no ahorra nada: lo que compra es ver las casas sobre pilotes iluminadas desde el balcón y el pueblo vacío al amanecer.</p></div>'+
  '<div class="xcard"><h4>Furong: recinto de pago, unos 108 yuanes</h4><p>El pueblo entero es área escénica de pago: unos 108 yuanes en taquilla (menos comprándola online), válida 3 días con entradas y salidas, con registro facial y pasaporte. Dormir dentro NO exime de pagarla, pero es la única forma de quedarse con la cascada iluminada cuando se van los autobuses, y el hotel gestiona el registro. El espectáculo nocturno va incluido.</p></div>'+
  '<div class="xcard"><h4>Wangxian: 140 yuanes que se ahorran durmiendo dentro</h4><p>Entrada de 140 yuanes, de 08:00 a 23:00, con las luces desde las 19:45. Aquí sí: los alojamientos de dentro del valle incluyen la entrada y dan el desfiladero iluminado sin hora de cierre. En Booking casi no hay oferta de dentro: lo de dentro se reserva por Trip.com y con meses.</p></div>'+
  '</div>'+
  '<div class="tw" style="margin-top:20px"><table><thead><tr><th>Pueblo</th><th>Alojamiento</th><th class="n">Nota</th><th>La baza nocturna</th><th>Reserva</th></tr></thead><tbody>'+
  '<tr><td><b>Fenghuang</b></td><td><a href="https://www.booking.com/hotel/cn/wang-jiang-shan-ju-jing-pin-min-su.es.html" target="_blank" rel="noopener">Wang Jiang Reclusive Boutique Inn</a></td><td class="n">9,8 · 639</td><td>Terrazas sobre el río, en alto y fuera del ruido de los bares</td><td>Booking</td></tr>'+
  '<tr><td><b>Fenghuang</b></td><td><a href="https://www.booking.com/hotel/cn/feng-huang-gu-cheng-lan-mao-lin-jiang-ke-zhan.es.html" target="_blank" rel="noopener">Lazy Cat Riverside Inn</a></td><td class="n">9,5 · 355</td><td>Primera línea del Tuojiang: desde el balcón se ve el espectáculo nocturno, lo dicen sus reseñas en español</td><td>Booking</td></tr>'+
  '<tr><td><b>Fenghuang</b></td><td><a href="https://www.booking.com/hotel/cn/he-tang-yue-she-min-su-xue-qiao-dian.es.html" target="_blank" rel="noopener">Hetang Yueshe Homestay (Xueqiao)</a></td><td class="n">9,7 · 56</td><td>Pegado al puente de nieve, ubicación de 10</td><td>Booking</td></tr>'+
  '<tr><td><b>Fenghuang</b></td><td><a href="https://www.booking.com/hotel/cn/feng-huang-gu-cheng-mo-nai-xing-wan-jiang-jing-min-su.es.html" target="_blank" rel="noopener">Monet Starry Night River View B&B</a></td><td class="n">9,8 · 36</td><td>Vistas a la torre Wanming iluminada sobre el río</td><td>Booking</td></tr>'+
  '<tr><td><b>Furong</b></td><td><a href="https://www.booking.com/hotel/cn/yong-shun-xian-fu-rong-zhen-tu-si-xuan-fu-ting-yuan-min-su-dian.es.html" target="_blank" rel="noopener">Tusi Xuanfu Courtyard Waterfall Guesthouse</a></td><td class="n">8,8 · 27</td><td>Sus reseñas: posiblemente las mejores vistas de todo Furong, con terraza nocturna sobre la cascada</td><td>Booking</td></tr>'+
  '<tr><td><b>Furong</b></td><td><a href="https://www.booking.com/hotel/cn/hua-zhu-bai-he-hua-gu-ke-zhan.es.html" target="_blank" rel="noopener">Floral Hotel Baihe Huagu Inn</a></td><td class="n">9,4 · 27</td><td>El mejor valorado del pueblo, a 100 metros del corazón del recinto</td><td>Booking</td></tr>'+
  '<tr><td><b>Furong</b></td><td>Wangcun Caotang Inn (el del viaje original)</td><td class="n">·</td><td>Vistas a la cascada y la recepción donde se encarga el coche con chófer</td><td>Trip.com (no está en Booking)</td></tr>'+
  '<tr><td><b>Wangxian</b></td><td>Yangxian Village, dentro del valle (el del viaje original)</td><td class="n">·</td><td>Entrada incluida y el valle iluminado para los huéspedes; check-in a las 17:00</td><td>Trip.com</td></tr>'+
  '<tr><td><b>Wangxian</b></td><td>Casas del acantilado (Cliff Homestay), dentro del valle</td><td class="n">·</td><td>La iluminación de las 19:45 desde la propia habitación, colgada de la pared de granito</td><td>Trip.com o canal oficial</td></tr>'+
  '<tr><td><b>Wangxian</b></td><td><a href="https://www.booking.com/hotel/cn/wang-xian-gu-qing-chuan-xing-guan-min-su.es.html" target="_blank" rel="noopener">Qingchuanxingguan</a></td><td class="n">9,2 · 217</td><td>La mejor opción que sí está en Booking: junto a la puerta del valle (la entrada no va incluida)</td><td>Booking</td></tr>'+
  '<tr><td><b>Wangxian</b></td><td><a href="https://www.booking.com/hotel/cn/wang-xian-shan-she-min-su.es.html" target="_blank" rel="noopener">Wangxian Shanshe Homestay</a></td><td class="n">9,3 · 121</td><td>Terraza con vistas a la montaña, junto al recinto</td><td>Booking</td></tr>'+
  '</tbody></table></div>'+
  '<h3 class="xh" style="margin-top:34px">Los hoteles, ya probados</h3>'+
  '<p class="xlede">Los diez alojamientos del viaje original, reservados por Trip.com con desayuno incluido (precios totales de octubre de 2026 para dos personas; media de 61 euros por noche). Valen tal cual como lista de partida.</p>'+
  '<div class="tw"><table><thead><tr><th>Ciudad</th><th>Hotel</th><th class="n">Noches</th><th class="n">Total</th><th>El detalle que importa</th></tr></thead><tbody>'+
  '<tr><td><b>Pekín</b></td><td>Liveforturna Hotel (Yabaolu)</td><td class="n">3</td><td class="n">239 €</td><td>Bufé desde las 06:30, clave los días de madrugón</td></tr>'+
  '<tr><td><b>Xi\'an</b></td><td>Center Hotel (torre de la Campana)</td><td class="n">3</td><td class="n">110 €</td><td>Al lado del barrio musulmán</td></tr>'+
  '<tr><td><b>Chengdú</b></td><td>Guilaiqi Boutique (Chunxi Road)</td><td class="n">3</td><td class="n">96 €</td><td>El bufé abre a las 07:30: para los pandas, desayuno para llevar</td></tr>'+
  '<tr><td><b>Chongqing</b></td><td>Holiday Riverside (Jiefangbei)</td><td class="n">2</td><td class="n">85 €</td><td>A diez minutos a pie de Hongyadong</td></tr>'+
  '<tr><td><b>Fenghuang</b></td><td>Secluded Qian Mansion</td><td class="n">1</td><td class="n">76 €</td><td>Dentro del casco antiguo, junto al río</td></tr>'+
  '<tr><td><b>Furong</b></td><td>Wangcun Caotang Inn</td><td class="n">1</td><td class="n">109 €</td><td>Vistas a la cascada; el coche a Zhangjiajie se encarga aquí</td></tr>'+
  '<tr><td><b>Zhangjiajie</b></td><td>Thousand Hotel</td><td class="n">1</td><td class="n">36 €</td><td>A un kilómetro del teleférico de Tianmen</td></tr>'+
  '<tr><td><b>Wulingyuan</b></td><td>Tianchong Yunhai Resort</td><td class="n">2</td><td class="n">60 €</td><td>Bufé desde las 06:30, pensado para madrugar al parque</td></tr>'+
  '<tr><td><b>Wangxian</b></td><td>Yangxian Village (dentro del valle)</td><td class="n">1</td><td class="n">150 €</td><td>Incluye la entrada al valle; check-in a las 17:00</td></tr>'+
  '<tr><td><b>Shanghái</b></td><td>Meta Tree Hotel (plaza del Pueblo)</td><td class="n">5</td><td class="n">382 €</td><td>Metro directo a Hongqiao por la línea 2</td></tr>'+
  '</tbody></table></div>',
 may:{
  sub:"Shanghái · Wangxian · Zhangjiajie · Furong · Fenghuang · Chongqing · Xi'an · Pekín",
  pitch:"Los diez destinos de un viaje real de 22 noches, comprimidos a diez días e invertidos para que la Terracota y la Muralla caigan después del Golden Week. Es la ruta más densa de las siete: cada noche se duerme en un sitio que por sí solo justificaría el viaje, y los avisos de estaciones, ventas y madrugones vienen resueltos de serie.",
  yes:["Terracota","Gran Muralla","Zhangjiajie","Valle de Wangxian","Fenghuang y Furong","Chongqing de noche"],
  no:["Sin pandas","Sin Shenzhen","Sin Ciudad Prohibida","Pekín y Shanghái exprés"],
  warnTitle:"La única ruta que pisa un parque nacional en pleno Golden Week",
  warn:"Invertir el orden protege la Terracota y la Muralla, que caen el 10 y el 11 de mayo, pero deja el parque de Zhangjiajie en los días 5 y 6, dentro del Golden Week: la cola del ascensor Bailong puede pasar de dos horas. Se gestiona madrugando (primera franja de las 07:00, subir por Tianzi si el Bailong está imposible) y comprando las entradas en el minuto en que se abra la venta. Si no queréis veros ahí esos días, las rutas 4 a 7 esquivan el problema.",
  legs:[["shanghai","wangxian","tren",480,"2 h 40 + 1 h de coche"],["wangxian","zhangjiajie","tren",900,"6 h"],["zhangjiajie","furong","bus",95,"1 h 15"],["furong","fenghuang","tren",60,"34 min"],["fenghuang","chongqing","tren",480,"3 h 30"],["chongqing","xian","tren",700,"5 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 15"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shanghái",img:"bund_1",cap:"El Bund y Pudong enfrente, un siglo mirándose",x:"Llegáis al amanecer con el directo del sábado. Paseo por el Bund, la Concesión Francesa a pie y el jardín Yu. Al caer la noche, el skyline de Pudong encendido desde la orilla. A la cama pronto, que mañana empieza el viaje de verdad."},
  {d:"Lun 3",t:"El valle de los inmortales",img:"wangxian_1",cap:"El desfiladero de Wangxian, con las pasarelas colgadas del acantilado",x:"Tren de media mañana a Shangrao (ojo: se sale de Hongqiao, no de Shanghai Sur) y una hora de coche hasta Wangxian. Se duerme dentro del valle: la entrada de 140 yuanes va incluida y, cuando los autobuses se van, el desfiladero iluminado (se enciende a las 19:45) se queda solo para los que duermen allí.",m:["tren","Shanghái a Shangrao 2 h 40, más 1 h de coche"]},
  {d:"Mar 4",t:"Travesía a las montañas de Avatar",img:"wangxian_2",cap:"El puente de farolillos sobre el cañón de Wangxian",x:"Mañana por el valle antes de que lleguen los autobuses y tren directo a Zhangjiajie Oeste, unas seis horas cruzando Hunan. Hay cuatro directos al día: este billete se compra en el primer minuto de la venta. Noche en Wulingyuan, a pie de parque.",m:["tren","Shangrao a Zhangjiajie Oeste, unas 6 h"]},
  {d:"Mié 5",t:"Parque Avatar, con estrategia",img:"wulingyuan_1",cap:"Los pilares de Yuanjiajie, los de la película",x:"Golden Week: primera franja de las 07:00 y a correr. Si la cola del ascensor Bailong pasa de una hora, se le da la vuelta al día: arriba por el teleférico de Tianzi y el Bailong para bajar a partir de las 16:00, cuando se vacía. La entrada vale cuatro días y los buses internos van incluidos."},
  {d:"Jue 6",t:"Tianmen, la puerta del cielo",img:"tianmen_1",cap:"Los 999 escalones hasta la Puerta del Cielo",x:"Mudanza en Didi a Zhangjiajie ciudad y franja de las 14:00 en Tianmen (la última que dejan entrar es la de las 16:00). Carretera de las 99 curvas, pasarelas de cristal y los 999 escalones. El tramo alto del teleférico sigue en obras: se sube con teleférico, bus y escaleras mecánicas. Arriba hace 5 a 10 grados menos.",m:["bus","Didi de Wulingyuan a Zhangjiajie ciudad, 45 min","stay"]},
  {d:"Vie 7",t:"Furong, el pueblo sobre la cascada",img:"furong_1",cap:"Furong: dos mil años construido encima de un salto de agua",x:"Coche con chófer hasta Furong, encargado la víspera en recepción con precio cerrado: en este ramal los trenes de la mañana directamente no existen. El pueblo entero es recinto de pago (unos 108 yuanes, valen 3 días) y de noche la cascada iluminada ruge debajo, ya sin autobuses.",m:["bus","Coche con chófer a Furong, 1 h 15"]},
  {d:"Sáb 8",t:"Fenghuang, la ciudad fénix",img:"fenghuang_1",cap:"Casas sobre pilotes en el río Tuojiang",x:"Última mañana de cascada y tren de 34 minutos a Fenghuang. La estación se llama Fenghuang Gucheng, y el buscador por ruta de Ctrip devuelve aquí cero trenes por un fallo suyo, no por falta de trenes. Atardecer sobre el Tuojiang y la ciudad vieja encendida reflejándose en el agua.",m:["tren","Furongzhen a Fenghuang Gucheng, 34 min"]},
  {d:"Dom 9",t:"Hongyadong y la ciudad vertical",img:"chongqing_1",cap:"Hongyadong: trece pisos de casas apiladas sobre el río",x:"Callejones de Fenghuang al amanecer, sin tours, y tren directo a Chongqing, con pocos directos al día: comprar el primer minuto. Ojo al bajar: Chongqing tiene cuatro estaciones. De noche, Hongyadong encendido visto desde el puente Qiansimen.",m:["tren","Fenghuang Gucheng a Chongqing Este, 3 h 30"]},
  {d:"Lun 10",t:"Terracota en orden inverso",img:"terracota_2",cap:"Fosa 1 del Mausoleo del Primer Emperador Qin",x:"Tren de la mañana a Xi'an, unas cinco horas, y entrada a los Guerreros a las 13:30, como recomiendan las guías locales: fosos 3, 2 y 1 en orden inverso, a contracorriente de todos los tours de la mañana. Cena en el barrio musulmán.",m:["tren","Chongqing a Xi'an Norte, unas 5 h"]},
  {d:"Mar 11",t:"AVE, Muralla y a casa",img:"mutianyu_1",cap:"Mutianyu: telesilla de subida y tobogán de bajada",x:"AVE de las 08:00 a Pekín (sale de Xi'an Norte y llega a Beijingxi) y directos a Mutianyu: telesilla a la torre 6, paseo hasta la 12, que suele estar vacía, y bajada en tobogán, que con lluvia no funciona. Cena en Qianmen y al aeropuerto: el vuelo a Madrid sale a la 01:55.",m:["tren","Xi'an a Pekín 4 h 30, y Didi a Mutianyu"]}]},
 ago:{
  sub:"Pekín · Xi'an · Chengdú · Chongqing · Fenghuang · Furong · Zhangjiajie · Wangxian · Shanghái",
  pitch:"La versión de agosto respeta el orden original del viaje en que se basa y recupera lo que en mayo no cabía: Ciudad Prohibida, pandas en Chengdú y una parada más larga en casi cada sitio. Son los mismos diez destinos con los deberes hechos: estaciones, ventas de billetes y madrugones vienen resueltos de serie.",
  yes:["Terracota","Gran Muralla","Ciudad Prohibida","Pandas","Zhangjiajie","Fenghuang y Furong","Valle de Wangxian","Chongqing"],
  no:["Sin Shenzhen","Sin Ruta de la Seda","Shanghái en una tarde"],
  warnTitle:"El agosto más duro de las siete rutas",
  warn:"Chongqing es una de las ciudades horno de China y pasa de 38 grados con humedad; Zhangjiajie suma unos 18 días de lluvia; los pandas de Chengdú se meten en salas climatizadas en cuanto pasa de 26 grados, así que solo funcionan antes de las 10:00; y la costa de Shanghái está en plena temporada de tifones. La ruta se hace, pero con el manual de agosto: madrugar siempre, horas centrales a la sombra y las noches para los espectáculos.",
  legs:[["beijing","mutianyu","bus",70,"1 h 15"],["beijing","xian","tren",1200,"4 h 30"],["xian","chengdu","tren",700,"3 h 40"],["chengdu","chongqing","tren",300,"1 h 40"],["chongqing","fenghuang","tren",480,"4 h"],["fenghuang","furong","tren",60,"34 min"],["furong","zhangjiajie","bus",95,"1 h 15"],["zhangjiajie","wangxian","tren",900,"5 h 50"],["wangxian","shanghai","tren",480,"2 h 40"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Pekín",img:"hutong_1",cap:"Los hutongs de Gulou, el Pekín a pie de calle",x:"El directo de Air China aterriza al amanecer. Maletas en recepción (el check-in no abre hasta las 14:00), desayuno de baozi y día suave por los hutongs de Gulou y el lago Houhai. Si el cuerpo aguanta, bajada de bandera en Tiananmen, que tiene reserva propia gratuita con franja."},
  {d:"Lun 16",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Telesilla a la torre 6 y tobogán de bajada",x:"Lunes de Muralla porque la Ciudad Prohibida cierra los lunes. Telesilla hasta la torre 6, caminata hasta la 12, que suele estar casi vacía, y bajada en un tobogán de 1.580 metros. El combo bueno es telesilla más tobogán: el teleférico de cabina sube a la torre 14 y ahí no hay tobogán.",m:["bus","Pekín a Mutianyu, 1 h 15"]},
  {d:"Mar 17",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias y ni un centímetro de sombra",x:"Reservada siete días antes a las 20:00 hora china, las 14:00 en España. Truco heredado del viaje original: no se entra cruzando Tiananmen, que está vallada y pide su propia reserva; se rodea por el Templo Ancestral, dos yuanes y sin cola. De sur a norte y remate en la colina de Jingshan."},
  {d:"Mié 18",t:"AVE a Xi'an",img:"xianwall_1",cap:"La muralla Ming de Xi'an, 14 kilómetros en bici",x:"Tren de las 07:55 desde Beijingxi (cuidado: hay trenes parecidos desde Fengtai y Qinghe que no son vuestra estación). Cuatro horas y media, maletas en consigna y tarde de muralla en bici cuando afloja el calor. De noche, el barrio musulmán.",m:["tren","Pekín a Xi'an, 4 h 30"]},
  {d:"Jue 19",t:"Terracota a contracorriente",img:"terracota_2",cap:"Ocho mil figuras y ninguna cara repetida",x:"Entrada a las 13:30 y fosos en orden inverso, 3, 2 y 1, esquivando los tours de la mañana. La mañana, para el museo de Shaanxi con aire acondicionado. Carrito eléctrico en el jardín Lishan: en agosto los 2,5 km a pie no tienen ninguna gracia."},
  {d:"Vie 20",t:"Tren a Chengdú",img:"chengdu_2",cap:"Casas de té: el deporte nacional de Sichuan",x:"Tres horas y media de tren hasta Chengdú Este. Tarde de casas de té en el parque del Pueblo, limpieza de oídos tradicional incluida si os atrevéis, y hotpot de Sichuan por la noche, empezando por el picante suave.",m:["tren","Xi'an a Chengdú, 3 h 40"]},
  {d:"Sáb 21",t:"Pandas antes de las diez",img:"panda_1",cap:"La base de cría de Chengdú, en la primera hora",x:"En la puerta a las 07:30. En agosto no es un consejo, es la única opción: en cuanto pasa de 26 grados los pandas se meten en salas climatizadas. De 08:00 a 10:00 desayunan fuera. Después, tarde en Chunxi Road o excursión al Buda de Leshan si quedan piernas."},
  {d:"Dom 22",t:"Chongqing, la ciudad horno",img:"chongqing_2",cap:"Chongqing de noche, rascacielos apilados entre dos ríos",x:"Una hora y cuarenta minutos de tren a Chongqing Norte. Aviso serio: Chongqing tiene cuatro estaciones y mañana se sale de otra distinta. Tarde en el pueblo antiguo de Ciqikou cuando afloje el sol y, de noche, Hongyadong encendido desde el puente Qiansimen.",m:["tren","Chengdú a Chongqing, 1 h 40"]},
  {d:"Lun 23",t:"De Chongqing a la ciudad fénix",img:"fenghuang_1",cap:"El río Tuojiang al atardecer, con las casas sobre pilotes",x:"Mañana de monorraíl en Liziba, que atraviesa un edificio de viviendas, y tren del mediodía a Fenghuang desde Chongqing Este, que está a 21 km de donde llegasteis: el error de estación más fácil del viaje. Solo hay tres directos al día. Llegada justo para el atardecer y las luces del río.",m:["tren","Chongqing Este a Fenghuang Gucheng, 4 h"]},
  {d:"Mar 24",t:"Fenghuang y Furong",img:"furong_1",cap:"La cascada de Furong, iluminada por la noche",x:"Fenghuang al amanecer, cuando los callejones son de los locales, y tren de 34 minutos a Furongzhen (se escribe todo junto al buscarlo). En este ramal no hay trenes por la mañana: el primero sale hacia mediodía, y no es un fallo de la app. El pueblo es recinto de pago (unos 108 yuanes, 3 días) y la noche con la cascada encendida va incluida.",m:["tren","Fenghuang Gucheng a Furongzhen, 34 min"]},
  {d:"Mié 25",t:"Tianmen, tarde y noche",img:"tianmen_1",cap:"La carretera de las 99 curvas, vista desde arriba",x:"Coche con chófer a Zhangjiajie, encargado la víspera en recepción con precio cerrado (aquí Didi no es fiable y el primer tren útil sale por la tarde). Franja de las 14:00 en Tianmen: pasarelas de cristal, 999 escalones y el espectáculo de luces de 18:30 a 21:00.",m:["bus","Coche con chófer a Zhangjiajie, 1 h 15"]},
  {d:"Jue 26",t:"Parque Avatar completo",img:"wulingyuan_1",cap:"Yuanjiajie y el pilar Aleluya, entre la niebla",x:"Mudanza a Wulingyuan a las 07:00 y al parque: ascensor Bailong, Yuanjiajie y los miradores de Tianzi, bajando en teleférico. En agosto la montaña está 5 a 10 grados más fresca que la ciudad, y si llueve, la niebla entre los pilares es mejor foto que el cielo azul.",m:["bus","Didi de Zhangjiajie a Wulingyuan, 45 min","stay"]},
  {d:"Vie 27",t:"El tren más crítico y Wangxian",img:"wangxian_1",cap:"El desfiladero de Wangxian, con las pasarelas colgadas del acantilado",x:"El tren de las 09:51 a Shangrao es el tramo con menos plazas del viaje: cuatro directos al día, comprado en el primer minuto. Check-out anticipado y fuera del hotel a las 08:10. Seis horas de tren, una de coche y noche dentro del valle iluminado, con la entrada de 140 yuanes incluida.",m:["tren","Zhangjiajie Oeste a Shangrao, 5 h 50"]},
  {d:"Sáb 28",t:"Wangxian de día y el Bund de noche",img:"shanghai_1",cap:"Pudong desde el Bund, la última postal del viaje",x:"Mañana por el desfiladero antes de que lleguen los autobuses y tren de las 13:48 a Shanghái Hongqiao (en esa búsqueda aparecen trenes a Shanghai Sur que no son el vuestro). Noche de despedida en el Bund y vuelo de madrugada a Madrid: en Zaragoza el domingo.",m:["tren","Shangrao a Shanghái, 2 h 40"]}]}},

{id:2,name:"El triángulo clásico",hex:"#B8195C",hexm:"#FB7CA9",curve:.13,classic:true,
 sub:"El primer viaje a China de toda la vida",
 may:{
  sub:"Shanghái · Suzhou · Hangzhou · Xi'an · Pekín",
  pitch:"El primer viaje a China de toda la vida: Shanghái, los Guerreros, la Ciudad Prohibida y la Muralla. Es el circuito que hace todo el mundo, y por algo es. El aviso es serio: también es el que peor encaja con vuestras fechas.",
  yes:["Muralla en Mutianyu","Terracota","Ciudad Prohibida","Shanghái","Todo en tren"],
  no:["Sin Shenzhen","Sin desierto","Sin naturaleza","El más masificado"],
  legs:[["shanghai","suzhou","tren",100,"30 min"],["shanghai","hangzhou","tren",170,"1 h"],["shanghai","xian","tren",1500,"6 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shanghái",img:"bund_1",cap:"El Bund, fachada colonial a un lado del río y Pudong al otro",x:"Llegada al amanecer en vuelo directo desde Barcelona o Madrid. El Bund al atardecer es el contraste que define la ciudad. Cena en la antigua concesión francesa."},
  {d:"Lun 3",t:"Shanghái entera",img:"shanghai_1",cap:"Pudong: en 1990 esto eran campos de arroz",x:"Pudong, el Museo de Shanghái y Tianzifang. Shanghái aguanta bien el Golden Week porque es enorme y no depende de un solo monumento con aforo."},
  {d:"Mar 4",t:"Suzhou, los jardines",img:"suzhou_1",cap:"Jardín del Administrador Humilde, patrimonio de la Unesco",x:"Media hora de tren. Suzhou conserva los mejores jardines clásicos chinos, paisajes en miniatura diseñados entre los siglos XI y XIX.",m:["tren","Shanghái a Suzhou, 30 min"]},
  {d:"Mié 5",t:"Hangzhou y el Lago del Oeste",img:"hangzhou_1",cap:"El Lago del Oeste, mil años de jardín construido",x:"El lago que los poetas chinos llevan un milenio describiendo, con diques, pagodas e islas artificiales.",m:["tren","Shanghái a Hangzhou, 1 h"]},
  {d:"Jue 6",t:"Tren a Xi'an",img:"crh_1",cap:"Seis horas a 300 km/h cruzando China",x:"Día de traslado, lo mejor que se puede hacer el último día del festivo. Por la tarde, el barrio musulmán de Xi'an.",m:["tren","Shanghái a Xi'an, 6 h"]},
  {d:"Vie 7",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna con la misma cara",x:"Primer día limpio tras el Golden Week, por eso la ruta va en este orden y no al revés. Por la tarde, la muralla de Xi'an en bici."},
  {d:"Sáb 8",t:"Tren a Pekín",img:"tiantan_1",cap:"Templo del Cielo: a las siete de la mañana es un parque de barrio",x:"Cuatro horas y media de tren. Por la tarde, el Templo del Cielo y los hutongs de Gulou en bici.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Dom 9",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Desde 2026 no se venden entradas en taquilla. Hay que reservar online con pasaporte, el cupo es de 40.000 al día y se abre solo siete días antes a las 20:00 hora de Pekín."},
  {d:"Lun 10",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: restaurada, con teleférico y tobogán de bajada",x:"La versión cómoda de la Muralla. Más gente que en Gubeikou, pero se llega en hora y media y no hay que caminar quince kilómetros.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Mar 11",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"El jardín imperial donde la corte huía del calor: tres kilómetros cuadrados de lago artificial cavados a mano. Vuelo de madrugada."}]},
 ago:{
  sub:"Shanghái · Suzhou · Hangzhou · Huangshan · Xi'an · Pekín · Datong",
  pitch:"Con cuatro días más el clásico gana dos cosas que lo mejoran mucho en verano: las Montañas Amarillas, que a 1.860 metros son el refugio climático del este de China, y las grutas de Yungang en Datong, patrimonio de la Unesco y muy poco visitadas por extranjeros.",
  yes:["Muralla en Mutianyu","Terracota","Ciudad Prohibida","Shanghái","Huangshan","Grutas de Yungang"],
  no:["Sin Shenzhen","Sin desierto","El más masificado"],
  warnTitle:"El clásico en agosto: calor y colas a la vez",
  warn:"Shanghái en agosto pasa de 35 grados con humedad altísima y es temporada de tifones. Xi'an llega a 40. Y las vacaciones escolares chinas llenan justamente estos sitios durante todo el mes. Lo que salva la versión de agosto es Huangshan: a 1.860 metros se está entre 8 y 10 grados más fresco, y es donde se refugia medio Shanghái.",
  legs:[["shanghai","suzhou","tren",100,"30 min"],["shanghai","hangzhou","tren",170,"1 h"],["hangzhou","huangshan","tren",280,"1 h 30"],["huangshan","xian","avion",1000,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"],["beijing","datong","tren",290,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shanghái",img:"bund_1",cap:"El Bund, fachada colonial a un lado y Pudong al otro",x:"Llegada al amanecer en directo desde Barcelona o Madrid. El Bund al anochecer, que en agosto es cuando se puede estar en la calle."},
  {d:"Lun 16",t:"Shanghái entera",img:"shanghai_1",cap:"Pudong: en 1990 esto eran campos de arroz",x:"Pudong y el Museo de Shanghái por la mañana, Tianzifang y la concesión francesa al caer la tarde. Con 35 grados y humedad, el plan es museo a mediodía y calle de noche."},
  {d:"Mar 17",t:"Suzhou, los jardines",img:"suzhou_1",cap:"Jardín del Administrador Humilde, patrimonio de la Unesco",x:"Media hora de tren. Los mejores jardines clásicos chinos, pensados justamente como refugio de sombra y agua para el verano.",m:["tren","Shanghái a Suzhou, 30 min"]},
  {d:"Mié 18",t:"Hangzhou y el Lago del Oeste",img:"hangzhou_1",cap:"El Lago del Oeste, mil años de jardín construido",x:"Diques, pagodas e islas artificiales. En agosto los lotos están en flor, que es la estampa clásica del lago.",m:["tren","Shanghái a Hangzhou, 1 h"]},
  {d:"Jue 19",t:"Subida a Huangshan",img:"huangshan_1",cap:"Mar de nubes desde lo alto de las Montañas Amarillas",x:"Hora y media de tren y se sube a 1.860 metros. Es la montaña que sale en toda la pintura clásica china: pinos retorcidos, granito y mar de nubes. Se duerme arriba.",m:["tren","Hangzhou a Huangshan, 1 h 30"]},
  {d:"Vie 20",t:"Amanecer sobre el mar de nubes",img:"huangshan_1",cap:"Los pinos de Huangshan sobre el granito",x:"Amanecer desde la cumbre, que es la razón de dormir arriba, y bajada por la otra vertiente. Ocho o diez grados menos que en Shanghái.",m:["avion","Huangshan a Xi'an, 2 h"]},
  {d:"Sáb 21",t:"Xi'an, muralla y barrio musulmán",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Muralla en bici al amanecer, 14 km de circuito cerrado, y barrio musulmán de noche. Las horas centrales, a la sombra."},
  {d:"Dom 22",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna con la misma cara",x:"A primera hora sí o sí: en agosto Xi'an llega a 40 grados y las fosas están cubiertas pero sin climatizar.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Lun 23",t:"Pekín, Templo del Cielo",img:"tiantan_1",cap:"A las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi y cantando ópera, y hutongs de Gulou en bici."},
  {d:"Mar 24",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Reserva obligatoria con pasaporte siete días antes, cupo de 40.000 y sin taquilla. En agosto se agota en minutos. Sin sombra dentro: entrada a primera hora."},
  {d:"Mié 25",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: teleférico de subida y tobogán de bajada",x:"La Muralla cómoda, a hora y media de Pekín. En agosto se va al abrir y se baja antes de mediodía.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Jue 26",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"Precisamente el sitio donde la corte imperial huía del calor de Pekín: tres kilómetros cuadrados de lago artificial y galerías cubiertas."},
  {d:"Vie 27",t:"Datong y las grutas de Yungang",img:"yungang_1",cap:"Yungang: 51.000 estatuas budistas talladas en el siglo V",x:"Dos horas de tren al oeste. Cincuenta y una mil estatuas excavadas en arenisca en el siglo V, patrimonio de la Unesco y con una décima parte de la gente que hay en Pekín.",m:["tren","Pekín a Datong, 2 h"]},
  {d:"Sáb 28",t:"Monasterio Colgante y vuelta",img:"yungang_1",cap:"Las grutas de Yungang, en Datong",x:"El Monasterio Colgante de Hengshan, encajado en la pared de un barranco desde hace 1.500 años, y vuelta a Pekín para el vuelo de madrugada.",m:["tren","Datong a Pekín, 2 h"]}]}},

{id:3,name:"El clásico ampliado",hex:"#33608E",hexm:"#8CBCE8",curve:-.07,classic:true,
 sub:"El circuito de dos semanas de las agencias",
 may:{
  sub:"Shenzhen · Yangshuo · Longji · Chengdú · Xi'an · Pekín",
  pitch:"El circuito clásico completo, el de dos semanas de las agencias, comprimido en diez días: tecnología, los karst de Guilin, las terrazas de arroz, los pandas, los Guerreros y la Muralla. Es el que más cosas distintas mete sin salirse de lo conocido.",
  yes:["Muralla en Mutianyu","Terracota","Pandas de Chengdú","Shenzhen","Karst de Guilin","Minorías zhuang y yao"],
  no:["Sin desierto","Sin Zhangjiajie","Todo muy visitado"],
  legs:[["shenzhen","guilin","tren",700,"2 h 40"],["guilin","yangshuo","bus",65,"1 h 15"],["guilin","longji","bus",100,"2 h"],["guilin","chengdu","avion",1100,"1 h 45"],["chengdu","xian","tren",700,"3 h 10"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, robotaxi por Nanshan y Gangxia North. Un día en la China de 2027 antes de irse a la China de postal."},
  {d:"Lun 3",t:"Tren a Guilin y Yangshuo",img:"yangshuo_1",cap:"Los karst de Yangshuo saliendo de los campos de arroz",x:"Menos de tres horas de tren y cambia el país entero: torres de caliza de doscientos metros brotando de los campos.",m:["tren","Shenzhen a Guilin, 2 h 40"]},
  {d:"Mar 4",t:"Río Li en balsa de bambú",img:"lijiang_1",cap:"El paisaje que sale en el billete de 20 yuanes",x:"Bajar el río Li en balsa entre los karst es literalmente la imagen del billete de 20 yuanes. Por la tarde, bici por el campo entre pueblos."},
  {d:"Mié 5",t:"Terrazas de Longji",img:"longji_1",cap:"Terrazas talladas hace 650 años por los zhuang y los yao",x:"Dos horas al norte. Una ladera entera esculpida en terrazas desde la dinastía Yuan. En mayo están inundadas y reflejan el cielo.",m:["bus","Guilin a Longji, 2 h"]},
  {d:"Jue 6",t:"Vuelo a Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Hora y tres cuartos de vuelo. Tarde de casas de té en el parque del Pueblo y hotpot sichuanés por la noche.",m:["avion","Guilin a Chengdú, 1 h 45"]},
  {d:"Vie 7",t:"Pandas al amanecer",img:"panda_2",cap:"La base de cría de Chengdú, doscientos y pico ejemplares",x:"A la base a las 7:30, la única franja en la que los pandas están despiertos y comiendo. A partir de las diez se duermen y llega el grueso de la gente."},
  {d:"Sáb 8",t:"Tren a Xi'an",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter chino tiene 58 trazos",x:"Tres horas de tren atravesando las montañas Qinling por túnel. Tarde de muralla en bici y noche en el barrio musulmán.",m:["tren","Chengdú a Xi'an, 3 h 10"]},
  {d:"Dom 9",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada rostro es distinto, se cree que retratos reales",x:"Ocho mil figuras enterradas 2.200 años hasta que unos campesinos cavaron un pozo en 1974. Tren nocturno a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Lun 10",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu, la sección restaurada más manejable",x:"Teleférico para subir, tobogán para bajar y hora y media desde Pekín.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Mar 11",t:"Ciudad Prohibida y Templo del Cielo",img:"gugong_2",cap:"La entrada a la Ciudad Prohibida",x:"Reserva obligatoria con pasaporte, siete días antes y sin taquilla. Por la tarde el Templo del Cielo y los hutongs. Vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Yangshuo · Longji · Chengdú · Leshan · Xi'an · Pekín",
  pitch:"El clásico ampliado con los cuatro días que le faltaban: dos jornadas de verdad en Yangshuo, el Buda gigante de Leshan y un día extra en Pekín. En agosto las terrazas de Longji están verdes y crecidas, que para muchos es mejor foto que inundadas.",
  yes:["Muralla en Mutianyu","Terracota","Pandas de Chengdú","Shenzhen","Karst de Guilin","Longji","Buda de Leshan"],
  no:["Sin desierto","Sin Zhangjiajie","Tifones en el tramo sur"],
  warnTitle:"Ojo al tramo sur en agosto",
  warn:"Shenzhen, Guilin y Yangshuo están de lleno en la zona de tifones, con 4 a 6 de media en agosto y cancelaciones habituales de vuelos y trenes. Como ese tramo va al principio, un tifón os come días de karst pero no os hace perder el vuelo internacional, que sale de Pekín. Aun así, seguro con cobertura de cancelación.",
  legs:[["shenzhen","guilin","tren",700,"2 h 40"],["guilin","yangshuo","bus",65,"1 h 15"],["guilin","longji","bus",100,"2 h"],["guilin","chengdu","avion",1100,"1 h 45"],["chengdu","leshan","tren",130,"1 h"],["chengdu","xian","tren",700,"3 h 10"],["xian","beijing","tren",1200,"4 h 30"],["beijing","mutianyu","bus",70,"1 h 30"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, robotaxi por Nanshan y Gangxia North. Un día en la China de 2027 antes de irse a la de postal."},
  {d:"Lun 16",t:"Shenzhen y tren a Guilin",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Mañana de DJI Sky City y reparto con dron. Por la tarde, menos de tres horas de tren y cambia el país entero.",m:["tren","Shenzhen a Guilin, 2 h 40"]},
  {d:"Mar 17",t:"Río Li en balsa de bambú",img:"lijiang_1",cap:"El paisaje que sale en el billete de 20 yuanes",x:"Bajar el río entre torres de caliza de doscientos metros. En agosto el río va crecido y verde, y hay que salir temprano por el calor."},
  {d:"Mié 18",t:"Yangshuo en bici",img:"yangshuo_1",cap:"Karst y campos de arroz alrededor de Yangshuo",x:"El día que no cabe en la versión de mayo: bici por el campo entre pueblos, la cueva de agua y el circuito de Yulong. Es como mejor se ve la zona."},
  {d:"Jue 19",t:"Terrazas de Longji",img:"longji_1",cap:"Terrazas talladas hace 650 años por los zhuang y los yao",x:"Dos horas al norte. En agosto están verdes y crecidas, con las aldeas zhuang y yao arriba del todo. Se duerme en la montaña, que refresca.",m:["bus","Guilin a Longji, 2 h"]},
  {d:"Vie 20",t:"Vuelo a Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Hora y tres cuartos de vuelo. Casas de té en el parque del Pueblo, donde los jubilados juegan al mahjong, y hotpot por la noche.",m:["avion","Guilin a Chengdú, 1 h 45"]},
  {d:"Sáb 21",t:"Pandas al amanecer",img:"panda_2",cap:"La base de cría de Chengdú, doscientos y pico ejemplares",x:"A la base a las 7:30, la única franja en la que están despiertos. A partir de las diez se duermen y llega el grueso de la gente."},
  {d:"Dom 22",t:"El Buda gigante de Leshan",img:"leshan_1",cap:"71 metros tallados en el acantilado en el siglo VIII",x:"Una hora de tren. El Buda de piedra más grande del mundo, excavado en el acantilado durante noventa años en el siglo VIII. Se ve desde barco y desde la escalera lateral.",m:["tren","Chengdú a Leshan, 1 h"]},
  {d:"Lun 23",t:"Tren a Xi'an",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Tres horas atravesando las montañas Qinling por túnel. Muralla en bici al atardecer y barrio musulmán de noche.",m:["tren","Chengdú a Xi'an, 3 h 10"]},
  {d:"Mar 24",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada rostro es distinto, se cree que retratos reales",x:"A primera hora: en agosto Xi'an llega a 40 grados. Ocho mil figuras enterradas 2.200 años hasta 1974.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Mié 25",t:"Pekín, Templo del Cielo y hutongs",img:"tiantan_1",cap:"A las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con tai chi y ópera, hutongs de Gulou en bici y el 798 por la tarde."},
  {d:"Jue 26",t:"Ciudad Prohibida",img:"gugong_2",cap:"9.000 estancias, el mayor conjunto palaciego del mundo",x:"Reserva con pasaporte siete días antes, cupo de 40.000 y sin taquilla. Entrada a primera hora, que dentro no hay sombra."},
  {d:"Vie 27",t:"Gran Muralla en Mutianyu",img:"mutianyu_1",cap:"Mutianyu: teleférico de subida y tobogán de bajada",x:"La Muralla cómoda, hora y media desde Pekín. Al abrir y de vuelta antes de mediodía.",m:["bus","Pekín a Mutianyu, 1 h 30"]},
  {d:"Sáb 28",t:"Palacio de Verano",img:"yiheyuan_1",cap:"El lago Kunming, excavado a mano en el siglo XVIII",x:"El jardín donde la corte huía del calor de Pekín, que en agosto se entiende perfectamente. Vuelo de madrugada."}]}},

{id:4,name:"La Ruta de la Seda",hex:"#B45309",hexm:"#F6B44E",curve:.11,rec:true,
 sub:"El corredor del Hexi de punta a punta",
 may:{
  sub:"Shenzhen · Zhangye · Jiayuguan · Dunhuang · Xi'an · Pekín",
  pitch:"El corredor del Hexi de punta a punta. Veis la Gran Muralla en sus dos extremos opuestos, el fuerte del desierto y el dragón de montaña, con 2.500 km de por medio. Es la ruta con menos aeropuertos y la que casi ningún español ha hecho.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Qinling"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","lanzhou","avion",1900,"3 h 30"],["lanzhou","zhangye","tren",550,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","xian","avion",1620,"2 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegáis al amanecer. Huaqiangbei son 35 mercados especializados y más de 115.000 negocios apilados en manzanas enteras de componentes, drones y placas. Al lado, la estación de metro de Gangxia North parece una nave. Cena en Shekou."},
  {d:"Lun 3",t:"Shenzhen a fondo",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Robotaxi de nivel 4 con Pony.ai por Nanshan sin nadie al volante, DJI Sky City, reparto con dron de Meituan y tiendas de robots humanoides. Por la noche, vuelo al noroeste.",m:["avion","Vuelo nocturno a Lanzhou, 3 h 30"]},
  {d:"Mar 4",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, 24 millones de años de sedimentos",x:"Tren hasta Zhangye. Las montañas de Danxia son capas de arenisca teñidas de óxidos que solo revientan de color con la luz baja: hay que ir a última hora de la tarde, no a mediodía.",m:["tren","Lanzhou a Zhangye, 3 h"]},
  {d:"Mié 5",t:"Jiayuguan, donde acababa China",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo occidental de la Muralla Ming",x:"La fortaleza que cerraba el imperio por el oeste. Más allá empezaba lo desconocido. Se sube a la Muralla Colgante trepando por la ladera y se llega a la Primera Atalaya, asomada al cañón del río Taolai.",m:["tren","Zhangye a Jiayuguan, 1 h 30. Después a Dunhuang"]},
  {d:"Jue 6",t:"Mogao y las dunas",img:"mogao_1",cap:"Grutas de Mogao, 492 cuevas de los siglos IV al XIV",x:"Mogao por la mañana: el mayor archivo de arte budista del planeta, mil años de murales en cuevas cavadas en el acantilado. Por la tarde, las dunas de Mingsha y el lago de la Media Luna, un oasis que lleva dos mil años sin ser tragado por la arena."},
  {d:"Vie 7",t:"Desierto puro",img:"yumen_1",cap:"Muralla Han en el paso de Yumen, barro y caña, hace 2.100 años",x:"El día más raro del viaje. Paso de Yumen, los restos de la Muralla Han (mil años más antigua que la de las postales, hecha de capas de barro y caña, y sin nadie alrededor) y el geoparque de Yardang al atardecer.",m:["avion","Vuelo nocturno a Xi'an, 2 h 30"]},
  {d:"Sáb 8",t:"Guerreros de Terracota",img:"terracota_2",cap:"Fosa 1 del Mausoleo del Primer Emperador Qin",x:"Primer día limpio tras el Golden Week. Ocho mil figuras, ninguna con la misma cara, custodiando a un emperador que llevaba 2.200 años enterrado cuando unos campesinos cavaron un pozo en 1974. Por la tarde, la muralla de Xi'an en bici."},
  {d:"Dom 9",t:"El único panda marrón del mundo",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco vivo",x:"A 70 km de Xi'an está el centro de Qinling, con 14 pandas de una subespecie distinta de la de Sichuan. Allí vive Qi Zai, el único panda marrón del mundo. Casi no va ningún occidental. Por la tarde, tren a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Lun 10",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar con hierba entre las almenas",x:"De Gubeikou a Jinshanling: entre 10 y 15 km caminando por muralla sin restaurar, torres derruidas y ni una tienda de recuerdos. Se duerme en una casa rural al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mar 11",t:"Amanecer sobre la muralla",img:"jinshanling_1",cap:"Jinshanling al amanecer, medio restaurada y medio salvaje",x:"Por esto se duerme allí. Se sube de noche y se ve salir el sol sobre la cresta, sin nadie. Vuelta a Pekín, últimas horas y vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Xining · Qinghai · Zhangye · Jiayuguan · Dunhuang · Xi'an · Pekín",
  pitch:"La versión de agosto añade cuatro días y algo que en mayo no existe: el altiplano de Qinghai. Mientras Xi'an pasa de 38 grados, Xining se queda en 22 y el lago Qinghai está a 3.200 metros. Es la única ruta que en agosto mejora en lugar de empeorar.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Qinling","Altiplano de Qinghai"],
  no:["Sin Zhangjiajie","Sin minorías"],
  warnTitle:"Por qué esta es la ruta de agosto",
  warn:"Todas las demás rutas sufren el verano chino. Esta lo aprovecha: el corredor de Gansu tiene 33 grados de día, 18 de noche y 6 mm de lluvia en todo el mes, y el altiplano de Qinghai es directamente un refugio climático a 22 grados. Es donde se va la gente de Pekín y Shanghái a escapar del calor, y por una vez tienen razón.",
  legs:[["shenzhen","xining","avion",2200,"4 h"],["xining","qinghai","bus",150,"2 h 30"],["qinghai","chaka","bus",140,"2 h"],["xining","zhangye","tren",500,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","xian","avion",1620,"2 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei, el mayor mercado de electrónica del mundo",x:"Llegada al amanecer. Huaqiangbei, 35 mercados especializados de componentes, drones y placas, y la estación de metro de Gangxia North. Hará 33 grados y una humedad brutal: es el día de aclimatarse a lo peor antes de subir al altiplano."},
  {d:"Lun 16",t:"Shenzhen tecnológica",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros",x:"Robotaxi de nivel 4 con Pony.ai por Nanshan, DJI Sky City, reparto con dron de Meituan y tiendas de robots humanoides. Por la noche, vuelo al altiplano.",m:["avion","Vuelo nocturno a Xining, 4 h"]},
  {d:"Mar 17",t:"Xining, 22 grados a 2.200 metros",img:"xining_1",cap:"Mezquita de Dongguan, uno de los grandes centros musulmanes del noroeste",x:"Bajáis de 33 grados con humedad a 22 grados secos. Xining es la puerta del Tíbet: mezquita de Dongguan, mercado nocturno de cordero y el monasterio de Kumbum a una hora. Día de aclimatación antes de subir a 3.200 metros."},
  {d:"Mié 18",t:"Lago Qinghai",img:"qinghai_1",cap:"El mayor lago salado de China, a 3.200 metros",x:"Cuatro veces el tamaño del lago de Ginebra, a 3.200 metros, con las montañas nevadas al fondo. Si venís en la ventana B (primera quincena) los campos de colza aún están en flor y la orilla es un mar amarillo.",m:["bus","Xining al lago Qinghai, 2 h 30"]},
  {d:"Jue 19",t:"Chaka, el espejo del cielo",img:"chaka_1",cap:"Chaka: costra de sal a 3.059 metros que refleja las nubes",x:"Un lago salado donde se camina sobre la costra blanca y el agua fina refleja el cielo entero. Vuelta a Xining por la noche.",m:["bus","Qinghai a Chaka y vuelta, 4 h"]},
  {d:"Vie 20",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, 24 millones de años de sedimentos",x:"Tren hacia el corredor del Hexi. Las franjas de arenisca teñidas de óxidos solo revientan de color con luz baja: hay que ir a última hora, nunca a mediodía.",m:["tren","Xining a Zhangye, 3 h"]},
  {d:"Sáb 21",t:"Jiayuguan, donde acababa China",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo occidental de la Muralla Ming",x:"La fortaleza que cerraba el imperio por el oeste. Muralla Colgante trepando la ladera y Primera Atalaya asomada al cañón del río Taolai. Tren a Dunhuang.",m:["tren","Zhangye a Jiayuguan 1 h 30, luego a Dunhuang"]},
  {d:"Dom 22",t:"Mogao y las dunas",img:"mogao_1",cap:"Grutas de Mogao, 492 cuevas de los siglos IV al XIV",x:"Las cuevas por la mañana, cuando aún no aprieta. Por la tarde las dunas de Mingsha y el lago de la Media Luna: en agosto el atardecer es a las 20:30, así que hay luz buena hasta tardísimo."},
  {d:"Lun 23",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, barro y caña de hace 2.100 años",x:"Día de desierto puro con 33 grados secos, que se llevan mucho mejor que los 33 húmedos de Shenzhen. El tramo de muralla más antiguo en pie y el geoparque de Yardang al atardecer.",m:["avion","Vuelo nocturno a Xi'an, 2 h 30"]},
  {d:"Mar 24",t:"Guerreros de Terracota",img:"terracota_2",cap:"Fosa 1 del Mausoleo del Primer Emperador Qin",x:"Xi'an en agosto pasa de 38 grados, así que los Guerreros a primera hora y la muralla en bici a última. Las horas centrales, museo o barrio musulmán a la sombra."},
  {d:"Mié 25",t:"El único panda marrón del mundo",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco vivo",x:"El centro de Qinling, a 70 km de Xi'an, con 14 pandas de una subespecie distinta y el único panda marrón del planeta. Está en montaña, así que se agradece. Cierra los lunes: hoy es miércoles.",m:["tren","Xi'an a Pekín por la tarde, 4 h 30"]},
  {d:"Jue 26",t:"Pekín viva",img:"tiantan_1",cap:"Templo del Cielo: a las siete de la mañana es un parque de barrio",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi y cantando ópera, hutongs de Gulou en bici y el 798 por la tarde. Agosto en Pekín son 32 grados y tormentas de tarde."},
  {d:"Vie 27",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"De Gubeikou a Jinshanling, entre 10 y 15 km por muralla sin restaurar. En agosto se sale al alba para evitar el calor y se lleva el doble de agua. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 28",t:"Amanecer sobre la muralla",img:"jinshanling_1",cap:"Jinshanling al amanecer, medio restaurada y medio salvaje",x:"Se sube de noche y se ve salir el sol sobre la cresta, sin nadie. Vuelta a Pekín, últimas horas y vuelo de madrugada."}]}},

{id:5,name:"La China del sur",hex:"#05684D",hexm:"#3FD79A",curve:.06,
 sub:"Aldeas dong y miao, Avatar y Terracota",
 may:{
  sub:"Shenzhen · Zhaoxing · Basha · Furong · Zhangjiajie · Xi'an · Pekín",
  pitch:"Aldeas dong y miao donde no se habla inglés, las montañas que inspiraron Avatar y los Guerreros. Casi todo va en tren de alta velocidad por el mismo corredor, sin volver atrás. Es la más auténtica en el sentido literal de la palabra.",
  yes:["Muralla","Terracota","Zhangjiajie","Minorías étnicas","Shenzhen"],
  no:["Sin Ruta de la Seda","Sin pandas"],
  legs:[["shenzhen","congjiang","tren",700,"3 h 30"],["congjiang","zhaoxing","bus",20,"25 min"],["zhaoxing","basha","bus",45,"1 h"],["basha","jishou","tren",400,"3 h"],["jishou","furong","tren",100,"40 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",900,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"De pueblo pesquero a 17 millones en cuarenta años",x:"Llegada al amanecer y día completo en Huaqiangbei y Nanshan. Es el contraste que da sentido al resto de la ruta: mañana estaréis en aldeas de madera sin ascensor."},
  {d:"Lun 3",t:"Shenzhen y salto a Guizhou",img:"shenzhen_2",cap:"Huaqiangbei, componentes y drones por manzanas enteras",x:"Mañana de tecnología: robotaxi, DJI, reparto con dron. Por la tarde, tren de alta velocidad a Congjiang y coche hasta Zhaoxing.",m:["tren","Shenzhen a Congjiang, 3 h 30"]},
  {d:"Mar 4",t:"Zhaoxing, la aldea dong",img:"dong_1",cap:"Torre del tambor dong, construida sin un solo clavo",x:"La mayor aldea dong de China: cinco torres del tambor, puentes del viento y la lluvia, y casas de madera apiladas en el valle. Caminata hasta Tang'an por las terrazas de arroz."},
  {d:"Mié 5",t:"Basha y las terrazas",img:"basha_1",cap:"Aldeas de Guizhou en las laderas",x:"Basha es la única comunidad de China autorizada a llevar armas de fuego. Los hombres se afeitan la cabeza con una hoz y llevan el moño tradicional. No es un espectáculo para turistas, es como viven."},
  {d:"Jue 6",t:"Furong, el pueblo sobre la cascada",img:"furong_1",cap:"Furong, pueblo tujia de 2.000 años sobre un salto de agua",x:"Tren hacia el norte, a Xiangxi. Furong lleva dos mil años ahí, literalmente construido encima de una cascada. Por la noche, a Zhangjiajie.",m:["tren","Congjiang a Jishou y Furong, 3 h 40"]},
  {d:"Vie 7",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares de arenisca de Wulingyuan entre la niebla",x:"Primer día tras el Golden Week, que es cuando las colas del ascensor Bailong se desinflan. Yuanjiajie y el pilar que rebautizaron como Hallelujah tras Avatar, y Tianzi Shan."},
  {d:"Sáb 8",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Más de 3.000 agujas de cuarcita de hasta 400 metros",x:"Yangjiajie, la parte salvaje: escaleras verticales talladas en la roca por donde no pasa ni la décima parte de la gente. Y el arroyo del Látigo Dorado por el fondo del cañón."},
  {d:"Dom 9",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, un arco natural de 130 metros",x:"El teleférico más largo del mundo, 7,5 km desde la propia ciudad. La carretera de las 99 curvas, los 999 escalones y las pasarelas de cristal clavadas en el acantilado.",m:["avion","Zhangjiajie a Xi'an, 2 h"]},
  {d:"Lun 10",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada guerrero tiene una cara distinta",x:"Día completo en Xi'an: los Guerreros por la mañana, la muralla en bici y el barrio musulmán al caer la tarde. Tren nocturno a Pekín.",m:["tren","Xi'an a Pekín, 4 h 30"]},
  {d:"Mar 11",t:"Gran Muralla de Jinshanling",img:"jinshanling_2",cap:"Jinshanling, la sección más fotogénica y la menos concurrida",x:"Día completo en la muralla con el bus directo desde Dongzhimen. Vuelta a Pekín por la tarde y vuelo de madrugada.",m:["bus","Pekín a Jinshanling, 2 h"]}]},
 ago:{
  sub:"Shenzhen · Zhaoxing · Basha · Dehang · Fenghuang · Furong · Zhangjiajie · Xi'an · Pekín",
  pitch:"Con cuatro días más entran Dehang y Fenghuang, y Zhangjiajie deja de ser una carrera. El problema es el clima: es la ruta que peor lo pasa en agosto, con 18 días de lluvia de media en Zhangjiajie y humedad alta en Guizhou.",
  yes:["Muralla","Terracota","Zhangjiajie completo","Minorías étnicas","Shenzhen","Fenghuang y Dehang"],
  no:["Sin Ruta de la Seda","Sin pandas","La que peor lleva agosto"],
  warnTitle:"Esta es la ruta que más sufre en agosto",
  warn:"Zhangjiajie promedia <b>18 días de lluvia</b> en agosto y Guizhou va con humedad alta constante. Lo que juega a favor: la montaña de Wulingyuan está entre 5 y 10 grados más fresca que la ciudad, la niebla tras la lluvia es justamente cuando los pilares se ven mejor, y la segunda quincena llueve menos que la primera. Si elegís esta ruta en agosto, id a la ventana A y meted un día de colchón.",
  legs:[["shenzhen","congjiang","tren",700,"3 h 30"],["congjiang","zhaoxing","bus",20,"25 min"],["zhaoxing","basha","bus",45,"1 h"],["basha","jishou","tren",400,"3 h"],["jishou","fenghuang","bus",60,"1 h"],["jishou","furong","tren",100,"40 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",900,"2 h"],["xian","beijing","tren",1200,"4 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"De pueblo pesquero a 17 millones en cuarenta años",x:"Llegada al amanecer. Huaqiangbei y Nanshan. Con 33 grados y humedad, el plan de agosto es interiores y noche: mercados con aire acondicionado de día y la bahía al anochecer."},
  {d:"Lun 16",t:"Shenzhen y salto a Guizhou",img:"shenzhen_2",cap:"Huaqiangbei, componentes y drones por manzanas enteras",x:"Mañana de robotaxi, DJI y reparto con dron. Por la tarde, tren a Congjiang y coche a Zhaoxing.",m:["tren","Shenzhen a Congjiang, 3 h 30"]},
  {d:"Mar 17",t:"Zhaoxing, la aldea dong",img:"dong_1",cap:"Torre del tambor dong, construida sin un solo clavo",x:"Cinco torres del tambor, puentes del viento y la lluvia, casas de madera apiladas. En agosto el arroz está verde y crecido, y por la noche refresca de verdad en el valle."},
  {d:"Mié 18",t:"Tang'an y las terrazas",img:"jiabang_1",cap:"Terrazas de arroz talladas durante siglos",x:"Caminata de Zhaoxing a Tang'an por las terrazas, hora y media subiendo. En agosto están en pleno verde. Se hace temprano, antes de que apriete."},
  {d:"Jue 19",t:"Basha, la aldea miao",img:"basha_1",cap:"Aldeas de Guizhou en las laderas",x:"La única comunidad de China autorizada a llevar armas de fuego. Los hombres se afeitan la cabeza con una hoz. No hay puesta en escena: es como viven."},
  {d:"Vie 20",t:"Dehang, cañón kárstico",img:"fenghuang_1",cap:"Xiangxi: aldeas miao entre paredes de caliza",x:"Tren al norte, a Xiangxi. Dehang es una aldea miao metida en un cañón de caliza con cascadas, y en agosto el agua es justamente lo que se agradece.",m:["tren","Congjiang a Jishou, 3 h"]},
  {d:"Sáb 21",t:"Fenghuang",img:"fenghuang_1",cap:"Casas sobre pilotes en el río Tuo",x:"El pueblo de casas sobre pilotes colgadas del río. Está muy turistificado, pero al amanecer y de noche con los faroles encendidos sigue mereciendo la pena.",m:["bus","Jishou a Fenghuang, 1 h"]},
  {d:"Dom 22",t:"Furong, el pueblo sobre la cascada",img:"furong_1",cap:"Furong, pueblo tujia de 2.000 años sobre un salto de agua",x:"Dos mil años construido literalmente encima de una cascada, que en agosto baja con todo el caudal del verano. Tren a Zhangjiajie.",m:["tren","Furong a Zhangjiajie, 30 min"]},
  {d:"Lun 23",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares de Wulingyuan entre la niebla",x:"Ascensor Bailong, Yuanjiajie y el pilar Hallelujah, Tianzi Shan. La niebla de después de la lluvia es exactamente cuando los pilares se ven como en las fotos."},
  {d:"Mar 24",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Más de 3.000 agujas de cuarcita de hasta 400 metros",x:"Yangjiajie, la parte salvaje de escaleras verticales por donde no pasa ni la décima parte de la gente, y el arroyo del Látigo Dorado por el fondo del cañón, que en agosto es la parte más fresca del parque."},
  {d:"Mié 25",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, arco natural de 130 metros",x:"Teleférico de 7,5 km desde la propia ciudad, carretera de las 99 curvas, 999 escalones y pasarelas de cristal en el acantilado."},
  {d:"Jue 26",t:"Gran Cañón y puente de cristal",img:"tianmen_1",cap:"Vista desde lo alto de Tianmen",x:"El día que solo cabe en la versión de agosto: el Gran Cañón de Zhangjiajie y el puente de cristal más largo del mundo, 430 metros a 300 de altura.",m:["avion","Vuelo nocturno a Xi'an, 2 h"]},
  {d:"Vie 27",t:"Guerreros de Terracota",img:"terracota_1",cap:"Cada guerrero tiene una cara distinta",x:"Guerreros a primera hora, que en agosto Xi'an llega a 38 grados. Muralla en bici al atardecer y barrio musulmán de noche.",m:["tren","Xi'an a Pekín por la noche, 4 h 30"]},
  {d:"Sáb 28",t:"Gran Muralla de Jinshanling",img:"jinshanling_2",cap:"Jinshanling, la más fotogénica y la menos concurrida",x:"Día completo en la muralla con el bus directo desde Dongzhimen, saliendo al alba. Vuelta a Pekín y vuelo de madrugada.",m:["bus","Pekín a Jinshanling, 2 h"]}]}},

{id:6,name:"El gran zigzag",hex:"#6541D6",hexm:"#A98CFF",curve:-.12,
 sub:"Máxima cobertura, máximo desgaste",
 may:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Xi'an · Zhangjiajie · Pekín",
  pitch:"Máxima cobertura: desierto, Terracota, Avatar y la Muralla dos veces. El precio son cinco vuelos internos y hacer la maleta seis veces en diez días. Con 32 años se aguanta, pero no es un viaje, es una campaña.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Zhangjiajie","Shenzhen"],
  no:["Sin minorías","Sin pandas","Cinco vuelos internos"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","xian","avion",1265,"2 h 30"],["xian","zhangjiajie","avion",900,"2 h"],["zhangjiajie","beijing","avion",1400,"2 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Llegáis al amanecer con el día entero por delante. Huaqiangbei son 35 mercados de componentes apilados en manzanas enteras, y a la vuelta de la esquina la estación de Gangxia North parece el interior de una nave."},
  {d:"Lun 3",t:"Shenzhen y salto al desierto",img:"shenzhen_3",cap:"Ping An Finance Center",x:"Robotaxi de nivel 4 con Pony.ai por Nanshan, sin nadie al volante, DJI Sky City y reparto con dron de Meituan. Por la noche, vuelo al otro extremo del país: 3.000 km de una sentada.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 4",t:"Mogao y Mingsha",img:"mingsha_1",cap:"El lago de la Media Luna entre las dunas de Mingsha",x:"Las 492 cuevas de Mogao por la mañana, mil años de pintura budista excavada en el acantilado. Por la tarde, las dunas de Mingsha, que suenan cuando sopla el viento, y el lago de la Media Luna."},
  {d:"Mié 5",t:"Yumen y Yardang",img:"yardang_1",cap:"Geoparque de Yardang, roca esculpida por el viento",x:"Paso de Yumen, donde se acababa el imperio, la Muralla Han de barro y caña de hace 2.100 años, y el geoparque de Yardang al atardecer, con la roca esculpida por el viento del Gobi.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Jue 6",t:"Jiayuguan",img:"jiayuguan_2",cap:"La fortaleza que cerraba el imperio por el oeste",x:"La fortaleza que cerraba China por el oeste, la Muralla Colgante trepando la ladera y la Primera Atalaya asomada al cañón del río Taolai, ochenta metros en vertical.",m:["avion","Jiayuguan a Xi'an, 2 h 30"]},
  {d:"Vie 7",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna repetida",x:"Primer día limpio tras el Golden Week, y por eso la ruta va en este orden y no al revés. Ocho mil figuras, ninguna con la misma cara. Por la tarde, los 14 km de muralla de Xi'an en bici.",m:["avion","Xi'an a Zhangjiajie, 2 h"]},
  {d:"Sáb 8",t:"Wulingyuan",img:"wulingyuan_1",cap:"Los pilares que inspiraron Avatar",x:"Ascensor Bailong, 326 metros clavados en el acantilado, y arriba Yuanjiajie con el pilar que rebautizaron como Hallelujah después de Avatar. Tianzi Shan al atardecer, cuando sube la niebla."},
  {d:"Dom 9",t:"Tianmen Shan",img:"tianmen_1",cap:"Vista desde lo alto de Tianmen",x:"El teleférico más largo del mundo, 7,5 km desde la propia ciudad. La carretera de las 99 curvas, los 999 escalones hasta la Puerta del Cielo y las pasarelas de cristal clavadas en la pared.",m:["avion","Zhangjiajie a Pekín, 2 h 30"]},
  {d:"Lun 10",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, sin restaurar",x:"De Gubeikou a Jinshanling: entre 10 y 15 km por muralla sin restaurar, con hierba entre las almenas y torres derruidas. Se duerme en una casa rural al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mar 11",t:"Amanecer y vuelta",img:"jinshanling_1",cap:"Amanecer en Jinshanling",x:"Se sube de noche para ver salir el sol sobre la cresta, sin nadie alrededor. Vuelta a Pekín, últimas horas y vuelo de madrugada."}]},
 ago:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Zhangye · Xi'an · Zhangjiajie · Pekín",
  pitch:"Con cuatro días más el Zigzag deja de ser una campaña militar: entra Zhangye, sobra un día en Xi'an y Zhangjiajie se hace en tres jornadas en vez de dos. Sigue siendo la ruta con más aviones, pero ya se puede respirar entre ellos.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Zhangjiajie completo","Shenzhen","Zhangye"],
  no:["Sin minorías","Sin pandas","Cuatro vuelos internos"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","zhangye","tren",220,"1 h 30"],["zhangye","xian","avion",1265,"2 h 30"],["xian","zhangjiajie","avion",900,"2 h"],["zhangjiajie","beijing","avion",1400,"2 h 30"],["beijing","jinshanling","bus",130,"2 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Llegada al amanecer. Huaqiangbei y la ciudad nueva, con 33 grados y humedad alta."},
  {d:"Lun 16",t:"Shenzhen tecnológica",img:"shenzhen_3",cap:"Ping An Finance Center",x:"Robotaxi, DJI Sky City, reparto con dron. Por la noche, vuelo al desierto.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 17",t:"Grutas de Mogao",img:"mogao_1",cap:"492 cuevas talladas entre los siglos IV y XIV",x:"El mayor archivo de arte budista del planeta. En verano la reserva es obligatoria y con cupo, así que va contratada de antemano."},
  {d:"Mié 18",t:"Mingsha y la Media Luna",img:"mingsha_1",cap:"El lago de la Media Luna entre las dunas",x:"Día tranquilo de dunas. En agosto anochece a las 20:30, así que se sube la duna a las siete de la tarde y todavía sobra luz."},
  {d:"Jue 19",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, barro y caña de hace 2.100 años",x:"El tramo de muralla más antiguo que sigue en pie y el geoparque de Yardang al atardecer. Tren a Jiayuguan.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Vie 20",t:"Jiayuguan",img:"jiayuguan_2",cap:"La fortaleza que cerraba el imperio por el oeste",x:"Fortaleza, Muralla Colgante trepando la ladera y Primera Atalaya sobre el cañón del Taolai.",m:["tren","Jiayuguan a Zhangye, 1 h 30"]},
  {d:"Sáb 21",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, capas de óxidos",x:"El día que no cabía en mayo. Danxia al atardecer, que es la única hora en que los colores funcionan de verdad.",m:["avion","Zhangye a Xi'an, 2 h 30"]},
  {d:"Dom 22",t:"Guerreros de Terracota",img:"terracota_2",cap:"Ocho mil figuras, ninguna repetida",x:"A primera hora: Xi'an en agosto llega a 38 grados y las fosas son cubiertas pero sin aire acondicionado."},
  {d:"Lun 23",t:"Xi'an y vuelo a Hunan",img:"xianfood_1",cap:"Biangbiang mian, cuyo carácter tiene 58 trazos",x:"Muralla en bici al amanecer, museo por la tarde y barrio musulmán de noche. Vuelo a Zhangjiajie.",m:["avion","Xi'an a Zhangjiajie, 2 h"]},
  {d:"Mar 24",t:"Wulingyuan, día uno",img:"wulingyuan_1",cap:"Los pilares que inspiraron Avatar",x:"Ascensor Bailong, Yuanjiajie, Tianzi Shan. La montaña está entre 5 y 10 grados más fresca que la ciudad."},
  {d:"Mié 25",t:"Wulingyuan, día dos",img:"wulingyuan_2",cap:"Agujas de cuarcita de hasta 400 metros",x:"Yangjiajie y el arroyo del Látigo Dorado por el fondo del cañón, que es la parte fresca del parque."},
  {d:"Jue 26",t:"Tianmen Shan",img:"tianmen_2",cap:"La Puerta del Cielo, arco natural de 130 metros",x:"Teleférico más largo del mundo, 99 curvas, 999 escalones y pasarelas de cristal.",m:["avion","Zhangjiajie a Pekín, 2 h 30"]},
  {d:"Vie 27",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, sin restaurar",x:"De Gubeikou a Jinshanling caminando, saliendo al alba por el calor. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 28",t:"Amanecer y vuelta",img:"jinshanling_1",cap:"Amanecer en Jinshanling",x:"Sol saliendo sobre la cresta, vuelta a Pekín y vuelo de madrugada."}]}},

{id:7,name:"Seda y panda",hex:"#0E7490",hexm:"#3ED0E6",curve:-.19,
 sub:"Desierto, Muralla, Terracota y pandas",
 may:{
  sub:"Shenzhen · Dunhuang · Jiayuguan · Pekín · Xi'an · Chengdú",
  pitch:"El desierto, la Muralla, los Guerreros y los pandas de Chengdú, rematado con el vuelo directo Chengdú a Madrid. Es la ruta que mejor cierra: acabáis en Sichuan comiendo picante y salís sin volver sobre vuestros pasos.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas de Chengdú","Sichuan"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","dunhuang","avion",3000,"5 h con escala"],["dunhuang","jiayuguan","tren",370,"2-3 h"],["jiayuguan","beijing","avion",2000,"3 h 30"],["beijing","jinshanling","bus",130,"2 h"],["beijing","xian","tren",1200,"4 h 30"],["xian","chengdu","tren",700,"3 h 10"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei",x:"Llegáis al amanecer. Huaqiangbei, el mayor mercado de electrónica del mundo con más de 115.000 negocios, y la estación de Gangxia North, que parece un decorado de ciencia ficción. Cena en Shekou."},
  {d:"Lun 3",t:"Shenzhen y salto al desierto",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Robotaxi de nivel 4 por Nanshan, DJI Sky City y tiendas de robots humanoides. Por la noche, vuelo al desierto: del delta más denso del planeta a la nada en cinco horas.",m:["avion","Shenzhen a Dunhuang, 5 h con escala"]},
  {d:"Mar 4",t:"Mogao y las dunas",img:"mogao_2",cap:"Murales de Mogao, mil años de pintura budista",x:"Mogao por la mañana: 492 cuevas y 45.000 metros cuadrados de mural. Por la tarde, las dunas de Mingsha y el lago de la Media Luna, un oasis que la arena no ha tragado en dos mil años."},
  {d:"Mié 5",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, hace 2.100 años",x:"Día de desierto puro. El paso de Yumen, el tramo de Muralla Han más antiguo que sigue en pie, hecho de capas de barro y caña, y el geoparque de Yardang al atardecer.",m:["tren","Dunhuang a Jiayuguan, 2-3 h"]},
  {d:"Jue 6",t:"Jiayuguan y salto a Pekín",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan",x:"La fortaleza del extremo occidental de la Muralla Ming, adonde se desterraba a la gente, la Muralla Colgante y la Primera Atalaya sobre el cañón del Taolai. Por la tarde, vuelo a Pekín.",m:["avion","Jiayuguan a Pekín, 3 h 30"]},
  {d:"Vie 7",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"Primer día tras el festivo, que es justo cuando la muralla se vacía. De Gubeikou a Jinshanling caminando, sin restaurar y sin una sola tienda de recuerdos. Se duerme al pie.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Sáb 8",t:"Amanecer en la muralla y Pekín",img:"tiantan_1",cap:"Templo del Cielo, a las siete de la mañana es un parque vivo",x:"Amanecer sobre la cresta y vuelta a Pekín. Tarde por los hutongs de Gulou en bici y el Templo del Cielo, que a esas horas es un parque de barrio. Tren nocturno a Xi'an.",m:["tren","Pekín a Xi'an, 4 h 30"]},
  {d:"Dom 9",t:"Guerreros de Terracota",img:"terracota_1",cap:"Ninguna figura repite rostro",x:"Los Guerreros por la mañana: ocho mil figuras enterradas 2.200 años hasta que unos campesinos cavaron un pozo en 1974. Muralla en bici por la tarde y barrio musulmán al anochecer."},
  {d:"Lun 10",t:"Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Tren rápido a Sichuan atravesando las montañas Qinling por túnel. Casas de té en el parque del Pueblo, donde los jubilados juegan al mahjong, y hotpot por la noche, un rito de tres horas.",m:["tren","Xi'an a Chengdú, 3 h 10"]},
  {d:"Mar 11",t:"Pandas al amanecer",img:"panda_1",cap:"Los pandas están activos de 7:30 a 10:00, después duermen",x:"A la base de cría a las 7:30, la única franja en la que los pandas están despiertos y comiendo; a partir de las diez se duermen. Por la noche, vuelo directo de Chengdú a Madrid.",m:["avion","Chengdú a Madrid, directo 12 h 20"]}]},
 ago:{
  sub:"Shenzhen · Xining · Qinghai · Zhangye · Jiayuguan · Dunhuang · Pekín · Xi'an · Chengdú",
  pitch:"La versión larga mete el altiplano de Qinghai al principio y el Buda de Leshan al final, y añade los pandas de Qinling además de los de Chengdú. Empieza a 3.200 metros y acaba comiendo picante en Sichuan, saliendo por el directo a Madrid.",
  yes:["Muralla, dos veces","Terracota","Ruta de la Seda","Shenzhen","Pandas, dos veces","Qinghai","Leshan"],
  no:["Sin Zhangjiajie","Sin minorías"],
  legs:[["shenzhen","xining","avion",2200,"4 h"],["xining","qinghai","bus",150,"2 h 30"],["xining","zhangye","tren",500,"3 h"],["zhangye","jiayuguan","tren",220,"1 h 30"],["jiayuguan","dunhuang","tren",370,"2-3 h"],["dunhuang","beijing","avion",2300,"4 h"],["beijing","jinshanling","bus",130,"2 h"],["beijing","xian","tren",1200,"4 h 30"],["xian","qinling","bus",70,"1 h 30"],["xian","chengdu","tren",700,"3 h 10"],["chengdu","leshan","tren",130,"1 h"]],
  days:[
  {d:"Dom 15",t:"Aterrizaje en Shenzhen",img:"shenzhen_2",cap:"Huaqiangbei",x:"Llegada al amanecer. Huaqiangbei y Gangxia North, con calor húmedo de 33 grados."},
  {d:"Lun 16",t:"Shenzhen y salto al altiplano",img:"shenzhen_1",cap:"El perfil de Shenzhen desde la bahía",x:"Robotaxi, DJI, drones de reparto. Vuelo nocturno a Xining, del calor húmedo a 22 grados secos.",m:["avion","Shenzhen a Xining, 4 h"]},
  {d:"Mar 17",t:"Xining y lago Qinghai",img:"qinghai_1",cap:"El mayor lago salado de China, a 3.200 metros",x:"Mezquita de Dongguan por la mañana y por la tarde al lago, cuatro veces el tamaño del lago de Ginebra con las montañas nevadas detrás.",m:["bus","Xining al lago Qinghai, 2 h 30"]},
  {d:"Mié 18",t:"Chaka, el espejo del cielo",img:"chaka_1",cap:"Costra de sal a 3.059 metros que refleja las nubes",x:"Se camina sobre la costra blanca y la lámina de agua refleja el cielo entero. Vuelta a Xining y tren al corredor del Hexi.",m:["tren","Xining a Zhangye, 3 h"]},
  {d:"Jue 19",t:"Montañas arcoíris de Zhangye",img:"zhangye_2",cap:"Danxia de Zhangye, capas de óxidos",x:"Danxia al atardecer, la única hora en que los colores funcionan. Tren a Jiayuguan.",m:["tren","Zhangye a Jiayuguan, 1 h 30"]},
  {d:"Vie 20",t:"Jiayuguan",img:"jiayuguan_1",cap:"Fortaleza de Jiayuguan, extremo oeste de la Muralla Ming",x:"Fortaleza, Muralla Colgante y Primera Atalaya sobre el cañón del Taolai. Tren a Dunhuang.",m:["tren","Jiayuguan a Dunhuang, 2-3 h"]},
  {d:"Sáb 21",t:"Mogao y las dunas",img:"mogao_2",cap:"Murales de Mogao, mil años de pintura budista",x:"Las 492 cuevas por la mañana y las dunas de Mingsha con el lago de la Media Luna al atardecer."},
  {d:"Dom 22",t:"Yumen, Muralla Han y Yardang",img:"yumen_1",cap:"Muralla Han en Yumen, hace 2.100 años",x:"Desierto puro: el tramo de muralla más antiguo en pie y el geoparque de Yardang. Vuelo nocturno a Pekín.",m:["avion","Dunhuang a Pekín, 4 h"]},
  {d:"Lun 23",t:"Pekín viva",img:"tiantan_1",cap:"Templo del Cielo, a las siete de la mañana es un parque vivo",x:"Templo del Cielo al amanecer con los abuelos haciendo tai chi, hutongs de Gulou en bici y 798 por la tarde."},
  {d:"Mar 24",t:"Gran Muralla salvaje",img:"gubeikou_1",cap:"Gubeikou, muralla sin restaurar",x:"De Gubeikou a Jinshanling caminando, saliendo al alba. Se duerme al pie de la muralla.",m:["bus","Pekín a Gubeikou, 2 h"]},
  {d:"Mié 25",t:"Amanecer y tren a Xi'an",img:"jinshanling_1",cap:"Jinshanling al amanecer",x:"Sol saliendo sobre la cresta sin nadie, vuelta a Pekín y tren rápido a Xi'an.",m:["tren","Pekín a Xi'an, 4 h 30"]},
  {d:"Jue 26",t:"Terracota y pandas de Qinling",img:"panda_3",cap:"Qi Zai, el único panda pardo y blanco del mundo",x:"Los Guerreros a primera hora y por la tarde el centro de Qinling, a 70 km, con el único panda marrón vivo. Cierra los lunes: hoy es jueves.",m:["bus","Xi'an a Qinling, 1 h 30"]},
  {d:"Vie 27",t:"Chengdú",img:"chengdu_2",cap:"Jinli, calle de casas de té y comida callejera",x:"Tren a Sichuan. Casas de té en el parque del Pueblo, donde los jubilados juegan al mahjong, y hotpot por la noche.",m:["tren","Xi'an a Chengdú, 3 h 10"]},
  {d:"Sáb 28",t:"Pandas y el Buda de Leshan",img:"leshan_1",cap:"El Buda de Leshan, 71 metros tallados en el acantilado",x:"Pandas a las 7:30, la única franja en que están despiertos, y por la tarde el Buda gigante de Leshan, a una hora en tren: 71 metros excavados en la roca en el siglo VIII. Vuelo directo a Madrid de madrugada.",m:["avion","Chengdú a Madrid, directo 12 h 20"]}]}},

{id:8,name:"Taiwán, Avatar y el futuro",hex:"#2563EB",hexm:"#70A5FF",curve:.12,main:true,
 sub:"Taipéi · Shenzhen · Fenghuang · Furong · Zhangjiajie · Xi'an · Shanghái",
 extra:'<h3 class="xh">Avisos operativos para esta ruta</h3>'+
  '<p class="xlede">Esta combinación conecta Taiwán con el corredor natural de Hunan y las capitales históricas y futuristas: sustituye las aglomeraciones de las megaciudades por dos joyas milenarias sobre el agua (Fenghuang y la cascada gigante de Furong) junto a las agujas de Avatar, la Terracota y Shanghái.</p>'+
  '<div class="xgrid">'+
  '<div class="xcard"><h4>Por qué Furong gana a Chongqing</h4><p>Para ver Hongyadong en Chongqing hacía falta un desvío de nueve horas de tren a una megaciudad de 32 millones de habitantes para ver un centro comercial iluminado. Furong, en cambio, está en la misma línea de tren de alta velocidad a solo 34 minutos de Fenghuang y 30 minutos de Zhangjiajie: un pueblo milenario auténtico suspendido sobre una colosal cascada de 60 metros que ruge iluminada de noche.</p></div>'+
  '<div class="xcard"><h4>El tren de alta velocidad en Hunan</h4><p>El ramal de alta velocidad de Xiangxi (a 350 km/h) une Shenzhen, Fenghuang, Furong y Zhangjiajie de forma fluida. Se viaja de centro a centro, con control de seguridad de cinco minutos y sin el riesgo de cancelaciones por tormentas que sufren los aeropuertos del sur en verano.</p></div>'+
  '<div class="xcard"><h4>El único vuelo necesario</h4><p>El salto de Taipéi a Shenzhen es un vuelo internacional regular de 1 h 45 min que cruza el estrecho. Es el único vuelo marítimo del viaje: a partir de Shenzhen todo el continente se recorre cómodamente en tren rápido hasta Shanghái.</p></div>'+
  '<div class="xcard"><h4>Fenghuang y las luces del río</h4><p>La joya de la ruta 1: las casas de madera sobre pilotes iluminadas sobre el Tuojiang. El casco antiguo es de acceso libre las 24 horas y los bares apagan la música hacia las 23:00. Se llega en AVE directo desde Shenzhen Norte (4 h 45 min) y se continúa a la mañana siguiente a Furong en solo 34 minutos.</p></div>'+
  '<div class="xcard"><h4>Zhangjiajie: el día 15 en el corazón del viaje</h4><p>El domingo 15 de agosto se vive en pleno Parque Nacional de Wulingyuan. En agosto los pilares de Yuanjiajie están entre 5 y 10 grados más frescos que las ciudades del valle, y la evaporación matinal genera el mar de niebla que deja los monolitos flotando en el vacío como en Avatar.</p></div>'+
  '<div class="xcard"><h4>Terracota en orden 3, 2, 1</h4><p>El consejo de oro para los Guerreros de Terracota en Xi\'an: entrar a las 13:30 y recorrer los pabellones al revés, empezando por la fosa 3 (el cuartel general), pasando por la 2 y rematando en la imponente fosa 1. Así vais a contracorriente de los grupos turísticos de autobús.</p></div>'+
  '<div class="xcard"><h4>La vuelta desde Shanghái</h4><p>El vuelo directo de China Eastern desde Shanghái Pudong a Madrid (MU709) sale a las 00:45 de la noche. Esto os permite disfrutar del sábado entero en Shanghái, cenar con calma frente al Bund iluminado y tomar el metro o el tren Maglev al aeropuerto sobre las 21:30.</p></div>'+
  '</div>',
 may:{
  sub:"Taipéi · Shenzhen · Fenghuang · Furong · Zhangjiajie · Xi'an · Shanghái",
  pitch:"La versión adaptada a diez días en mayo: Taipéi y el festival tecnológico de Shenzhen absorben el Golden Week mientras la metrópoli está vacía, para enlazar en tren rápido Fenghuang, la cascada de Furong, Zhangjiajie, Xi'an y Shanghái justo tras el 6 de mayo con los monumentos limpios de aglomeraciones.",
  yes:["Taiwán","Shenzhen tecnológico","Fenghuang sobre el río","Cascada de Furong","Montañas de Avatar","Guerreros de Terracota","Shanghái"],
  no:["Sin Jiufen","Sin Pekín","Ritmo comprimido a diez días"],
  warnTitle:"Orden calculado para esquivar el Golden Week",
  warn:"Shenzhen es una ciudad donde gran parte de la población procede de otras provincias y viaja a sus lugares de origen durante los festivos del 1 al 5 de mayo, por lo que la ciudad se vive sin atascos. El recorrido por Fenghuang, Furong, Zhangjiajie y Xi'an se realiza a partir del 6 de mayo, una vez finalizado el pico vacacional nacional.",
  legs:[["taipei","shenzhen","avion",800,"1 h 45"],["shenzhen","fenghuang","tren",750,"4 h 45"],["fenghuang","furong","tren",60,"34 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",680,"1 h 30"],["xian","shanghai","tren",1500,"6 h"]],
  days:[
  {d:"Dom 2",t:"Aterrizaje en Taipéi",img:"taipei_1",cap:"Taipéi de noche: la torre Taipei 101 dominando la cuenca",x:"Llegada al amanecer con el vuelo internacional. Check-in, templo Longshan y atardecer desde el mirador de la Montaña Elefante. Primera cena en el mercado nocturno de Raohe probando la comida callejera taiwanesa."},
  {d:"Lun 3",t:"Taipéi monumental",img:"taipei_1",cap:"El Memorial Chiang Kai-shek y el horizonte de Taipéi",x:"Memorial Chiang Kai-shek, plaza de la Libertad y compras de electrónica en el distrito tecnológico de Guanghua antes de preparar las maletas para cruzar el estrecho."},
  {d:"Mar 4",t:"Vuelo a Shenzhen en Golden Week",img:"shenzhen_2",cap:"Huaqiangbei en plena actividad",x:"Vuelo directo de hora y tres cuartos a Shenzhen. Ventaja estratégica: en pleno Golden Week la ciudad está despejada porque sus trabajadores se marchan a sus provincias. Huaqiangbei y robotaxis en Nanshan.",m:["avion","Taipéi a Shenzhen, 1 h 45"]},
  {d:"Mié 5",t:"Shenzhen tecnológico",img:"shenzhen_3",cap:"Ping An Finance Center y el distrito financiero",x:"Visita a las tiendas insignia de robótica, estación Gangxia North y preparativos para tomar el tren de alta velocidad hacia Hunan al día siguiente."},
  {d:"Jue 6",t:"AVE a Fenghuang, la ciudad fénix",img:"fenghuang_1",cap:"Casas sobre pilotes en el río Tuojiang al anochecer",x:"Primer día limpio tras el final del Golden Week. Tren de alta velocidad directo de Shenzhen Norte a Fenghuang Gucheng (4 h 45 min). Tarde de callejones y noche de casas tradicionales iluminadas sobre el río.",m:["tren","Shenzhen Norte a Fenghuang Gucheng, 4 h 45"]},
  {d:"Vie 7",t:"Furong: el pueblo sobre la cascada",img:"furong_1",cap:"Furong: casas tujia y la colosal cascada iluminada",x:"Tren rápido a Furongzhen (solo 34 min). Visita a las pasarelas detrás de la cascada de 60 metros y el pueblo milenario suspendido en el acantilado. Noche contemplando el salto de agua iluminado.",m:["tren","Fenghuang a Furongzhen, 34 min"]},
  {d:"Sáb 8",t:"Zhangjiajie y las montañas de Avatar",img:"wulingyuan_1",cap:"Los pilares de cuarcita de Yuanjiajie",x:"Tren rápido a Zhangjiajie (30 min). Ascensor Bailong a 326 metros de altura, miradores del pilar Aleluya de Avatar y teleférico de Tianzi Shan. Vuelo nocturno a Xi'an.",m:["avion","Zhangjiajie a Xi'an, 1 h 30"]},
  {d:"Dom 9",t:"Guerreros de Terracota en Xi'an",img:"terracota_2",cap:"Mausoleo de Qin Shi Huang",x:"Visita a los Guerreros a las 13:30 en orden 3, 2 y 1, muralla en bici al atardecer y AVE nocturno a 350 km/h hacia Shanghái.",m:["tren","Xi'an a Shanghái Hongqiao, 6 h"]},
  {d:"Lun 10",t:"Shanghái colonial y futurista",img:"bund_1",cap:"El Bund y Pudong al anochecer",x:"Concesión Francesa, jardín Yu, mirador de la Torre de Shanghái a 632 metros de altura y crucero nocturno por el río Huangpu frente al skyline iluminado."},
  {d:"Mar 11",t:"Despedida y vuelo a España",img:"shanghai_1",cap:"Pudong visto desde el río",x:"Últimas compras por Nanjing Road, tren Maglev a 430 km/h al aeropuerto de Pudong y vuelo directo de regreso a España, aterrizando el mismo día."}]},
 ago:{
  sub:"Taipéi · Jiufen · Shenzhen · Fenghuang · Furong · Zhangjiajie · Xi'an · Shanghái · Suzhou",
  pitch:"Diseñada a vuestra medida para volar el sábado 7 de agosto y regresar el domingo 22 (14 días en tierra con el domingo 15 en pleno viaje y aprovechando el festivo del 16 de agosto): une Taiwán y Shenzhen con las dos maravillas sobre el agua de Hunan (Fenghuang y la cascada de Furong), las montañas de Avatar, la Terracota en Xi'an y Shanghái sin perder horas en megaciudades abarrotadas.",
  yes:["Volar sáb 7 agosto","Taiwán y Jiufen","Shenzhen tecnológico","Fenghuang iluminado","Cascada de Furong","El 15 de agosto en Avatar","Guerreros de Terracota","Puente del 16 de agosto"],
  no:["Sin Pekín","Sin desvíos a Chongqing"],
  warnTitle:"Por qué Furong es la elección perfecta frente a Hongyadong",
  warn:"Para ver Hongyadong en Chongqing hacía falta desviarse nueve horas en tren a una urbe masificada de 32 millones de habitantes solo para ver una fachada comercial iluminada. Furongzhen, en cambio, está en la misma vía de alta velocidad entre Fenghuang y Zhangjiajie (a solo 34 minutos de la primera y 30 de la segunda): un pueblo milenario genuino colgado sobre una cascada de 60 metros de caída que ruge iluminada de noche, ganando tranquilidad y ahorrando medio día de trenes.",
  legs:[["taipei","shenzhen","avion",800,"1 h 45"],["shenzhen","fenghuang","tren",750,"4 h 45"],["fenghuang","furong","tren",60,"34 min"],["furong","zhangjiajie","tren",80,"30 min"],["zhangjiajie","xian","avion",680,"1 h 30"],["xian","shanghai","tren",1500,"6 h"],["shanghai","suzhou","tren",100,"30 min"]],
  days:[
  {d:"Dom 8",t:"Aterrizaje en Taipéi",img:"taipei_1",cap:"La torre Taipei 101 iluminada sobre la cuenca de Taipéi",x:"Vuelo desde España el sábado 7 de agosto. Aterrizaje el domingo 8 por la mañana. Check-in o maletas en consigna y primera inmersión urbana: el templo Longshan con sus espirales de incienso, el mirador de la Montaña Elefante al atardecer y cena callejera en el mercado nocturno de Raohe probando los famosos bollos de pimienta recién horneados y el auténtico té de burbujas."},
  {d:"Lun 9",t:"Jiufen y el valle de Shifen",img:"jiufen_1",cap:"Jiufen: callejones colgados del acantilado iluminados por farolillos",x:"Excursión a Jiufen y el valle de Shifen. En Shifen se lanzan los farolillos tradicionales de papel al cielo desde las vías del tren de Pingxi y se visita la cascada. En Jiufen, callejones empedrados sobre el océano Pacífico, la famosa casa de té Amei Tea House colgada del abismo y cientos de farolillos rojos que inspiraron la estética de Chihiro. Por la tarde, regreso a Taipéi para visitar la plaza de la Libertad y el animado barrio de Ximending."},
  {d:"Mar 10",t:"De Taipéi a la meca tecnológica",img:"shenzhen_2",cap:"Huaqiangbei: el epicentro del hardware mundial",x:"Mañana en Taipéi para visitar el Memorial Chiang Kai-shek. Al mediodía, vuelo directo de hora y tres cuartos a Shenzhen cruzando el estrecho. Es el único vuelo marítimo del viaje. Llegada a la capital del hardware: primera parada en la estación Gangxia North, cuyo techo futurista parece una nave espacial, y cena en el distrito de Futian.",m:["avion","Taipéi a Shenzhen, directo 1 h 45"]},
  {d:"Mié 11",t:"Shenzhen: la ciudad del futuro",img:"shenzhen_3",cap:"Ping An Finance Center, 599 metros en el centro de Shenzhen",x:"Día completo en la ciudad más innovadora del mundo: laberintos de componentes y prototipos en Huaqiangbei, paseo por Nanshan en un robotaxi autónomo sin conductor (con la app de Apollo Go o Pony.ai), visita a las torres de DJI y subida al mirador del Ping An Finance Center a casi 600 metros de altura. Al anochecer, espectáculo de miles de drones iluminando el skyline sobre la bahía."},
  {d:"Jue 12",t:"AVE a la ciudad fénix",img:"fenghuang_1",cap:"Casas sobre pilotes en el río Tuojiang al anochecer",x:"Comienza el recorrido en tren de alta velocidad: AVE matinal directo desde Shenzhen Norte a Fenghuang Gucheng (4 h 45 min cruzando Guangdong y las colinas de Hunan). Llegada por la tarde a la joya de la ruta 1: paseo por los callejones de piedra, cena junto al río Tuojiang y noche contemplando las casas sobre pilotes iluminadas reflejándose en el agua.",m:["tren","Shenzhen Norte a Fenghuang Gucheng, 4 h 45"]},
  {d:"Vie 13",t:"Furong: el pueblo sobre la cascada",img:"furong_1",cap:"Furong: la colosal cascada iluminada de noche bajo los aleros tradicionales",x:"Tren rápido de solo 34 minutos hasta Furongzhen. Llegada al pueblo milenario de la minoría Tujia, suspendido directamente sobre una impresionante cascada de 60 metros de ancho que ruge cayendo hacia el río You. Pasarela de piedra que pasa exactamente detrás de la cortina de agua, casas tradicionales colgadas de la pared de roca, prueba del famoso tofu de arroz en el puesto histórico 113 y noche inolvidable viendo el salto de agua y los aleros iluminados con farolillos rojos.",m:["tren","Fenghuang a Furongzhen, directo 34 min"]},
  {d:"Sáb 14",t:"Tianmen y llegada a las montañas de Avatar",img:"tianmen_2",cap:"La Puerta del Cielo: arco natural de 130 metros en lo alto de Tianmen",x:"Tren rápido de solo 30 minutos a Zhangjiajie Oeste. Subida directa al monte Tianmen: el teleférico de montaña más largo del mundo (7,5 km sobrevolando la ciudad y los valles cársticos), la pasarela de cristal Coiling Dragon suspendida a 1.400 metros de caída vertical sobre el abismo y los 999 escalones bajo la Puerta del Cielo. Traslado por la tarde al pueblo de Wulingyuan, a pie del parque nacional de Avatar.",m:["tren","Furongzhen a Zhangjiajie Oeste, directo 30 min"]},
  {d:"Dom 15",t:"Zhangjiajie: los pilares de Avatar",img:"wulingyuan_1",cap:"Yuanjiajie entre la niebla: el pilar Aleluya que inspiró la película",x:"El día 15 de agosto en pleno corazón del viaje: entrada a primera hora (07:30) al Parque Nacional de Wulingyuan. Ascensor Bailong adherido a la roca durante 326 metros y recorrido por los miradores de Yuanjiajie frente al pilar de Avatar. En agosto la niebla matinal deja los monolitos flotando en el vacío. Descenso en teleférico por Tianzi Shan. A última hora, vuelo corto a Xi'an (1 h 30 min) y primera cena en el barrio musulmán.",m:["avion","Zhangjiajie a Xi'an, directo 1 h 30"]},
  {d:"Lun 16",t:"Xi'an histórica y muralla en bici",img:"xianwall_1",cap:"Los 14 kilómetros de muralla Ming cerrada alrededor de Xi'an",x:"Festivo en Aragón que regala un día libre. Mañana en el Museo de Historia de Shaanxi, climatizado y con miles de reliquias de las dinastías Tang y Han, y visita a la Gran Mezquita del siglo VIII, oculta en un laberinto de patios tradicionales de madera. Al caer la tarde, alquiler de bicicletas para recorrer los 14 kilómetros completos de la muralla Ming al atardecer bajo los faroles rojos. Noche gastronómica de fideos biangbiang y pinchitos de cordero en los callejones iluminados."},
  {d:"Mar 17",t:"Guerreros de Terracota y AVE a Shanghái",img:"terracota_2",cap:"Fosa principal de los Guerreros de Terracota",x:"Visita a los Guerreros a las 13:30 recorriendo los fosos en orden inverso (3, 2 y 1) para esquivar las riadas de visitantes de la mañana. Por la tarde, tren de alta velocidad a 350 km/h directo hacia Shanghái (6 h). Llegada nocturna y primer paseo por el Bund.",m:["tren","Xi'an a Shanghái Hongqiao, 6 h a 350 km/h"]},
  {d:"Mié 18",t:"El Bund y la Concesión Francesa",img:"bund_1",cap:"El Bund y los rascacielos de Pudong frente a frente",x:"Día completo en Shanghái: mañanas de sombra en la arbolada Concesión Francesa, cafés de diseño en Tianzifang y arquitectura tradicional en el jardín Yu. Al atardecer, paseo por el paseo marítimo del Bund viendo encenderse la torre de Shanghái y la Perla Oriental al otro lado del río Huangpu."},
  {d:"Jue 19",t:"Pudong futurista y arte moderno",img:"shanghai_1",cap:"El distrito financiero de Pudong, capital económica de China",x:"Cruce a Pudong para subir a la Torre de Shanghái (632 m), el segundo rascacielos más alto del planeta, con su ascensor a 20,5 m/s y café en la librería de las nubes Duoyun Books en el piso 52 con vistas a la curva del Huangpu. Por la tarde, paseo artístico por el West Bund, antiguas fábricas ribereñas reconvertidas en galerías de arte contemporáneo, y crucero nocturno en barco por el río Huangpu."},
  {d:"Vie 20",t:"Escapada a Suzhou en alta velocidad",img:"suzhou_1",cap:"Jardín del Administrador Humilde, patrimonio de la Unesco",x:"Tren de alta velocidad de solo 25 minutos hasta Suzhou, la ciudad de los canales y los jardines clásicos de la dinastía Ming. Visita al Jardín del Administrador Humilde, paseo en barca tradicional de madera por los canales de Shantang Street y regreso a Shanghái a media tarde.",m:["tren","Shanghái a Suzhou ida y vuelta, 25 min"]},
  {d:"Sáb 21",t:"Última tarde y vuelo de vuelta",img:"shanghai_1",cap:"Despedida de Shanghái antes del vuelo nocturno",x:"Últimas horas para pasear por Xintiandi, preparar maletas con check-out tardío y saborear los mejores xiao long bao al vapor. A última hora, metro o tren de levitación magnética Maglev (a 430 km/h) al aeropuerto de Pudong. Vuelo directo de China Eastern a Madrid (sale a las 00:45) o Air China a Barcelona: aterrizaje en España el domingo 22 de agosto."}]}}
];
